// Generated from the media research (2026-10-06): freely licensed
// Wikimedia Commons photos (bundled in assets/people/, credited under
// each photo) and YouTube video IDs verified with YouTube's oEmbed
// endpoint (official channels where available).
const PEOPLE = {
 "torres": {
  "person": "Antonio de Torres Jurado (1817–1892)",
  "artist": "Unknown photographer",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Antonio_de_torres_jurado_001.jpg",
  "file": "Antonio de torres jurado 001.jpg",
  "img": "assets/people/torres.webp"
 },
 "torres-guitar": {
  "person": "A guitar by Torres, Museu de la Música de Barcelona",
  "artist": "sguastevi",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Guitarra_d%27Antonio_de_Torres,_MDMB_626,_al_Museu_de_la_M%C3%BAsica_de_Barcelona.jpg",
  "file": "Guitarra d'Antonio de Torres, MDMB 626, al Museu de la Música de Barcelona.jpg",
  "img": "assets/people/torres-guitar.webp"
 },
 "les-paul": {
  "person": "Les Paul",
  "artist": "William P. Gottlieb",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Les_Paul,_ca._Jan._1947_(William_P._Gottlieb_07001).jpg",
  "file": "Les Paul, ca. Jan. 1947 (William P. Gottlieb 07001).jpg",
  "img": "assets/people/les-paul.webp"
 },
 "brian-may": {
  "person": "Brian May",
  "artist": "Gage Skidmore",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Brian_May_(54760284093).jpg",
  "file": "Brian May (54760284093).jpg",
  "img": "assets/people/brian-may.webp"
 },
 "jimmy-page": {
  "person": "Jimmy Page",
  "artist": "Avda",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Jimmy_Page_at_the_Echo_music_award_2013.jpg",
  "file": "Jimmy Page at the Echo music award 2013.jpg",
  "img": "assets/people/jimmy-page.webp"
 },
 "robert-plant": {
  "person": "Robert Plant",
  "artist": "Raph_PH",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:RPlantSavGraceIpswich140324_(5_of_12)_(53589044022)_(cropped).jpg",
  "file": "RPlantSavGraceIpswich140324 (5 of 12) (53589044022) (cropped).jpg",
  "img": "assets/people/robert-plant.webp"
 },
 "don-felder": {
  "person": "Don Felder",
  "artist": "TaurusEmerald",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Don_Felder_Auto_Club_2023.jpg",
  "file": "Don Felder Auto Club 2023.jpg",
  "img": "assets/people/don-felder.webp"
 },
 "joe-walsh": {
  "person": "Joe Walsh",
  "artist": "Derek Russell",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Joe_Walsh_2019.jpg",
  "file": "Joe Walsh 2019.jpg",
  "img": "assets/people/joe-walsh.webp"
 },
 "slash": {
  "person": "Slash (musician)",
  "artist": "Kreepin Deth",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Slash_live_in_London_2022_(Cropped_-_upright).jpg",
  "file": "Slash live in London 2022 (Cropped - upright).jpg",
  "img": "assets/people/slash.webp"
 },
 "jimi-hendrix": {
  "person": "Jimi Hendrix",
  "artist": "Original photographer unknown",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Jimi_Hendrix_(1967)_(cropped).jpg",
  "file": "Jimi Hendrix (1967) (cropped).jpg",
  "img": "assets/people/jimi-hendrix.webp"
 },
 "django": {
  "person": "Django Reinhardt",
  "artist": "William P. Gottlieb / Adam Cuerden",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Django_Reinhardt_(Gottlieb_07301).jpg",
  "file": "Django Reinhardt (Gottlieb 07301).jpg",
  "img": "assets/people/django.webp"
 },
 "bb-king": {
  "person": "B.B. King",
  "artist": "Marco Tambara / Lightversus",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Bbking.jpg",
  "file": "Bbking.jpg",
  "img": "assets/people/bb-king.webp"
 },
 "eddie-van-halen": {
  "person": "Eddie Van Halen",
  "artist": "Carl Lender",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Eddie_Van_Halen_at_the_New_Haven_Coliseum.jpg",
  "file": "Eddie Van Halen at the New Haven Coliseum.jpg",
  "img": "assets/people/eddie-van-halen.webp"
 },
 "merle-travis": {
  "person": "Merle Travis",
  "artist": "Film screenshot (Sutton Pictures)",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Merle_Travis_in_Five_Minutes_to_Live_(1961).jpg",
  "file": "Merle Travis in Five Minutes to Live (1961).jpg",
  "img": "assets/people/merle-travis.webp"
 },
 "cf-martin": {
  "person": "Christian Frederick Martin (C. F. Martin & Company founder)",
  "artist": "Unknown author",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Christian_Frederick_Martin.jpg",
  "file": "Christian Frederick Martin.jpg",
  "img": "assets/people/cf-martin.webp"
 },
 "segovia": {
  "person": "Andrés Segovia",
  "artist": "Erling Mandelmann",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Andr%C3%A9s_Segovia_(1963)_by_Erling_Mandelmann.jpg",
  "file": "Andrés Segovia (1963) by Erling Mandelmann.jpg",
  "img": "assets/people/segovia.webp"
 },
 "tarrega": {
  "person": "Francisco Tárrega",
  "artist": "Unknown",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Francisco_tarrega_retrato.jpg",
  "file": "Francisco tarrega retrato.jpg",
  "img": "assets/people/tarrega.webp"
 },
 "paco-de-lucia": {
  "person": "Paco de Lucía",
  "artist": "Cornel Putan",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Paco_de_Luc%C3%ADa_4.jpg",
  "file": "Paco de Lucía 4.jpg",
  "img": "assets/people/paco-de-lucia.webp"
 },
 "joao-gilberto": {
  "person": "João Gilberto",
  "artist": "Tuca Vieira from São Paulo, Brazil",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Gilberto.jpg",
  "file": "João Gilberto.jpg",
  "img": "assets/people/joao-gilberto.webp"
 },
 "ali-farka-toure": {
  "person": "Ali Farka Touré",
  "artist": "Tagles",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Ali_Farka_Toure.jpg",
  "file": "Ali Farka Toure.jpg",
  "img": "assets/people/ali-farka-toure.webp"
 },
 "prince": {
  "person": "Prince",
  "artist": "Unknown author (1988 promotional photo)",
  "license": "Public domain",
  "licenseUrl": "",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Prince_promo_picture_(1988;_cropped_and_retouched).png",
  "img": "assets/people/prince.webp"
 },
 "george-harrison": {
  "person": "George Harrison",
  "artist": "John Kelly",
  "license": "Public domain",
  "licenseUrl": "",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:George-wa-portrait.jpg",
  "img": "assets/people/george-harrison.webp"
 }
};
const VIDEOS = {
 "les-paul": {
  "id": "FfkPaDmik10",
  "title": "Les Paul tours his Mahwah recording studio from an outtake of his documentary ‘Chasing Sound.’",
  "author_name": "Les Paul Official"
 },
 "brian-may-red-special": {
  "id": "vrz7nlkSt4k",
  "title": "Queen: The Guitar Solo (Episode 38)",
  "author_name": "Queen Official"
 },
 "stairway": {
  "id": "Ly6ZhQVnVow",
  "title": "Led Zeppelin - Stairway To Heaven (Live at Earl's Court 1975) [Official Video]",
  "author_name": "Led Zeppelin"
 },
 "hotel-california": {
  "id": "09839DpTctU",
  "title": "Eagles - Hotel California (Live 1977) (Official Video) [HD]",
  "author_name": "Eagles"
 },
 "november-rain": {
  "id": "8SbUC-UaAxE",
  "title": "Guns N' Roses - November Rain",
  "author_name": "GunsNRosesVEVO"
 },
 "segovia": {
  "id": "bcdS2hbpZcY",
  "title": "Andrés Segovia: Bach - Gavotte from 4th Lute Suite for guitar",
  "author_name": "Allegro Films"
 },
 "romance": {
  "id": "hhZjBd7l6HA",
  "title": "Alexandr Sokolkin plays Romance on Guitar | Siccas Media",
  "author_name": "SiccasGuitars"
 },
 "recuerdos": {
  "id": "fwjX-m4LkYk",
  "title": "Ana Vidovic plays Recuerdos de la Alhambra by Francisco Tárrega on a Jim Redgate classical guitar",
  "author_name": "SiccasGuitars"
 },
 "flamenco": {
  "id": "GayHfFTWdX0",
  "title": "Paco de Lucía | Live at Liège Guitar Festival | 1983",
  "author_name": "Qwest TV"
 },
 "bossa-nova": {
  "id": "Y0a0QuLEC8A",
  "title": "Chega de Saudade",
  "author_name": "João Gilberto - Topic"
 },
 "godfather-tremolo": {
  "id": "xFCYBWQlgqE",
  "title": "\"The Godfather\" for guitar (with a little tremolo)",
  "author_name": "Philip Glaser"
 },
 "slack-key": {
  "id": "rFxrfbQGTwY",
  "title": "Legend and Legacy: Hawaiian Slack-Key Guitar with Ledward Kaapana",
  "author_name": "Smithsonian Folklife"
 },
 "ali-farka-toure": {
  "id": "4mnAUe4c08o",
  "title": "Ali Farka Touré - Savane (Live at Bozar)",
  "author_name": "Ali Farka Touré"
 },
 "how-guitar-made": {
  "id": "PtsFibqgGzo",
  "title": "See How the D-28 is Handmade",
  "author_name": "Martin Guitar"
 },
 "prince-wmggw": {
  "id": "6SFNW5F8K9Y",
  "title": "Prince, Tom Petty, Steve Winwood, & More \"While My Guitar Gently Weeps\" | Rock Hall 2004 Induction",
  "author_name": "Rock & Roll Hall of Fame"
 },
 "creep": {"id": "XFkzRNyygfk", "title": "Radiohead - Creep", "author_name": "Radiohead"},
 "ed-sheeran-looping": {"id": "Q2CW9TZ81wo", "title": "Ed Sheeran: Tiny Desk Concert", "author_name": "NPR Music"},
 "the-a-team": {"id": "xADSSBs34is", "title": "Ed Sheeran - The A Team (Acoustic Boat Sessions)", "author_name": "Ed Sheeran"},
 "perfect": {"id": "9vDIzVuDzTs", "title": "Perfect (Acoustic)", "author_name": "Ed Sheeran - Topic"},
 "viva-la-vida": {"id": "vUnWFsc5WBU", "title": "Chris Martin “Viva la Vida” (Acoustic) on the Howard Stern Show (2016)", "author_name": "The Howard Stern Show"},
 "country-roads": {"id": "IUmnTfsY3hI", "title": "John Denver - Take Me Home, Country Roads (from The Wildlife Concert)", "author_name": "JohnDenverVEVO"},
 "linger": {"id": "sDK0xdiHBcQ", "title": "The Cranberries - Linger (Acoustic Version)", "author_name": "TheCranberriesVEVO"},
 "love-story": {"id": "8xg3vE8Ie_E", "title": "Taylor Swift - Love Story", "author_name": "Taylor Swift"},
 "let-it-be": {"id": "CGj85pVzRJs", "title": "The Beatles - Let It Be (Official Music Video) [Remastered 2015]", "author_name": "TheBeatlesVEVO"},
 "stand-by-me": {"id": "UiTwbwxbG2U", "title": "Stand by Me (Remastered 2015)", "author_name": "Ben E. King - Topic"},
 "someone-like-you": {"id": "NAc83CF8Ejk", "title": "Adele - Someone Like You (Live in Her Home)", "author_name": "Adele"},
 "no-woman-no-cry": {"id": "mZ6VezKMoRY", "title": "Bob Marley & The Wailers - No Woman, No Cry (Live At The Rainbow 4th June 1977)", "author_name": "BobMarleyVEVO"},
 "dont-stop-believin": {"id": "VcjzHMhBtf0", "title": "Journey - Don't Stop Believin' (Escape Tour 1981: Live In Houston)", "author_name": "journeyVEVO"},
 "my-funny-valentine": {"id": "tczRmxcEoow", "title": "Chet Baker - My Funny Valentine (Remastered 2004)", "author_name": "Chet Baker - Topic"},
 "jazz-loop": {"id": "otFVFLtRF_s", "title": "Herbie Hancock - Cantaloupe Island (Remastered 1999)", "author_name": "Herbie Hancock - Topic"},
 "bamboleo": {"id": "7qbEt_lSib4", "title": "Gipsy Kings - Bamboléo (Official Video)", "author_name": "gipsykingsVEVO"},
 "song-bad-guy": {"id": "DyDfgMOUjCI", "title": "Billie Eilish - bad guy", "author_name": "BillieEilishVEVO"},
 "song-last-christmas": {"id": "E8gmARGvPlI", "title": "Wham! - Last Christmas (Official Video)", "author_name": "WhamVEVO"},
 "song-all-i-want-for-christmas-is-you": {"id": "aAkMkVFwAoo", "title": "Mariah Carey - All I Want for Christmas Is You (Make My Wish Come True Edition)", "author_name": "MariahCareyVEVO"},
 "song-die-with-a-smile": {"id": "kPa7bsKwL-c", "title": "Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-blinding-lights": {"id": "4NRXx6U8ABQ", "title": "The Weeknd - Blinding Lights (Official Video)", "author_name": "TheWeekndVEVO"},
 "song-shape-of-you": {"id": "JGwWNGJdvx8", "title": "Ed Sheeran - Shape of You (Official Music Video)", "author_name": "Ed Sheeran"},
 "song-sweater-weather": {"id": "GCdwKhTtNNw", "title": "The Neighbourhood - Sweater Weather (Official Video)", "author_name": "TheNeighbourhoodVEVO"},
 "song-starboy": {"id": "34Na4j8AVgA", "title": "The Weeknd - Starboy ft. Daft Punk (Official Video) ft. Daft Punk", "author_name": "TheWeekndVEVO"},
 "song-as-it-was": {"id": "H5v3kku4y6Q", "title": "Harry Styles - As It Was (Official Video)", "author_name": "HarryStylesVEVO"},
 "song-someone-you-loved": {"id": "zABLecsR5UE", "title": "Lewis Capaldi - Someone You Loved", "author_name": "LewisCapaldiVEVO"},
 "song-sunflower": {"id": "ApXoWvfEYVU", "title": "Post Malone, Swae Lee - Sunflower (Spider-Man: Into the Spider-Verse)", "author_name": "PostMaloneVEVO"},
 "song-one-dance": {"id": "5LFB3qdmZBM", "title": "One Dance", "author_name": "Drake - Topic"},
 "song-stay": {"id": "kTJczUoc26U", "title": "The Kid LAROI, Justin Bieber - STAY (Official Video)", "author_name": "TheKidLAROIVEVO"},
 "song-believer": {"id": "7wtfhZwyrcc", "title": "Imagine Dragons - Believer (Official Music Video)", "author_name": "ImagineDragonsVEVO"},
 "song-i-wanna-be-yours": {"id": "nyuo9-OjNNg", "title": "I Wanna Be Yours", "author_name": "Arctic Monkeys - Topic"},
 "song-heat-waves": {"id": "mRD0-GxqHVo", "title": "Glass Animals - Heat Waves (Official Video)", "author_name": "GlassAnimalsVEVO"},
 "song-yellow": {"id": "yKNxeF4KMsY", "title": "Coldplay - Yellow (Official Video)", "author_name": "Coldplay"},
 "song-the-night-we-met": {"id": "KtlgYxa6BMU", "title": "Lord Huron - The Night We Met (Official Audio)", "author_name": "Lord Huron"},
 "song-closer": {"id": "0zGcUoRlhmw", "title": "The Chainsmokers - Closer (Official Video) ft. Halsey", "author_name": "ChainsmokersVEVO"},
 "song-riptide": {"id": "uJ_1HMAGb4k", "title": "Vance Joy - 'Riptide' Official Video", "author_name": "Mushroom"},
 "song-levitating": {"id": "TUVcZfQe-Kw", "title": "Dua Lipa - Levitating Featuring DaBaby (Official Music Video)", "author_name": "Dua Lipa"},
 "song-lucid-dreams": {"id": "mzB1VGEGcSU", "title": "Juice WRLD - Lucid Dreams (Official Music Video)", "author_name": "Lyrical Lemonade"},
 "song-photograph": {"id": "nSDgHBxUbVQ", "title": "Ed Sheeran - Photograph (Official Music Video)", "author_name": "Ed Sheeran"},
 "song-you-belong-with-me": {"id": "VuNIsY6JdUw", "title": "Taylor Swift - You Belong With Me", "author_name": "Taylor Swift"},
 "song-lover": {"id": "-BjZmE2gtdo", "title": "Taylor Swift - Lover (Official Music Video)", "author_name": "Taylor Swift"},
 "song-shake-it-off": {"id": "nfWlot6h_JM", "title": "Taylor Swift - Shake It Off", "author_name": "Taylor Swift"},
 "song-wildest-dreams": {"id": "IdneKLhsWOQ", "title": "Taylor Swift - Wildest Dreams", "author_name": "Taylor Swift"},
 "song-shallow": {"id": "bo_efYhYU2A", "title": "Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-million-reasons": {"id": "en2D_5TzXCA", "title": "Lady Gaga - Million Reasons (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-always-remember-us-this-way": {"id": "5vheNbQlsyU", "title": "Lady Gaga - Always Remember Us This Way (from A Star Is Born) (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-have-yourself-a-merry-little-christmas": {"id": "0vibMVTvaW0", "title": "Have Yourself A Merry Little Christmas", "author_name": "Judy Garland - Topic"},
 "song-thinking-out-loud": {"id": "lp-EO5I60KA", "title": "Ed Sheeran - Thinking Out Loud (Official Music Video)", "author_name": "Ed Sheeran"},
 "song-galway-girl": {"id": "87gWaABqGYs", "title": "Ed Sheeran - Galway Girl [Official Music Video]", "author_name": "Ed Sheeran"},
 "song-drop-it-like-it-s-hot": {"id": "GtUVQei3nX4", "title": "Snoop Dogg - Drop It Like It's Hot (Official Music Video) ft. Pharrell Williams", "author_name": "SnoopDoggVEVO"},
 "song-gin-and-juice": {"id": "fWCZse1iwE0", "title": "Snoop Dogg - Gin And Juice", "author_name": "SnoopDoggVEVO"},
 "song-young-wild-free": {"id": "Wa5B22KAkEk", "title": "Snoop Dogg & Wiz Khalifa - Young, Wild and Free ft. Bruno Mars [Official Video]", "author_name": "Wiz Khalifa"},
 "song-with-or-without-you": {"id": "ujNeHIo7oTE", "title": "U2 - With Or Without You (Official Music Video)", "author_name": "U2VEVO"},
 "song-i-m-yours": {"id": "EkHTsc9PU2A", "title": "Jason Mraz - I'm Yours (Official Video) [4K Remaster]", "author_name": "Jason Mraz"},
 "song-despacito": {"id": "kJQP7kiw5Fk", "title": "Luis Fonsi - Despacito ft. Daddy Yankee", "author_name": "LuisFonsiVEVO"},
 "song-let-her-go": {"id": "RBumgq5yVrA", "title": "Passenger | Let Her Go (Official Video)", "author_name": "Passenger"},
 "song-a-horse-with-no-name": {"id": "na47wMFfQCo", "title": "America - A Horse With No Name (Official Audio)", "author_name": "RHINO"},
 "song-knockin-on-heaven-s-door": {"id": "rm9coqlk8fY", "title": "Bob Dylan - Knockin' On Heaven's Door (Official Audio)", "author_name": "BobDylanVEVO"},
 "song-wonderwall": {"id": "bx1Bh8ZvH84", "title": "Oasis - Wonderwall (Official Video)", "author_name": "OasisVEVO"},
 "song-love-yourself": {"id": "oyEuk8j8imI", "title": "Justin Bieber - Love Yourself (PURPOSE : The Movement)", "author_name": "JustinBieberVEVO"},
 "song-count-on-me": {"id": "6k8cpUkKK4c", "title": "Bruno Mars - Count on Me (Official Lyric Video)", "author_name": "Bruno Mars"},
 "song-zombie": {"id": "R5SwRvAbpe8", "title": "Zombie (Acoustic Version)", "author_name": "The Cranberries - Topic"},
 "song-hey-soul-sister": {"id": "kVpv8-5XWOI", "title": "Train - Hey, Soul Sister (Official Video)", "author_name": "TrainVEVO"},
 "song-let-it-go": {"id": "YVVTZgwYwVo", "title": "Idina Menzel - Let It Go (from Frozen) (Official Video)", "author_name": "DisneyMusicVEVO"},
 "song-budapest": {"id": "f7raiIQ70iA", "title": "George Ezra - \"Budapest\" (Last.fm Sessions)", "author_name": "Last.fm"},
 "song-sweet-home-alabama": {"id": "-35W_FWCT9Q", "title": "Lynyrd Skynyrd - Sweet Home Alabama (Audio)", "author_name": "LynyrdSkynyrdVEVO"},
 "song-wonderful-tonight": {"id": "UprwkbzUX6g", "title": "Eric Clapton - Wonderful Tonight [Official Live]", "author_name": "Eric Clapton"},
 "song-over-the-rainbow": {"id": "V1bFr2SWP1I", "title": "OFFICIAL Somewhere over the Rainbow - Israel \"IZ\" Kamakawiwoʻole", "author_name": "Mountain Apple Company Inc"},
 "song-chasing-cars": {"id": "GemKqzILV4w", "title": "Snow Patrol - Chasing Cars (Official Video)", "author_name": "SnowPatrolVEVO"},
 "song-happy": {"id": "ZbZSe6N_BXs", "title": "Pharrell Williams - Happy (Official Video)", "author_name": "PharrellWilliamsVEVO"},
 "song-banana-pancakes": {"id": "YdgoG8hTMUw", "title": "Banana Pancakes", "author_name": "Jack Johnson - Topic"},
 "song-can-you-feel-the-love-tonight": {"id": "KjgWWjkNbhU", "title": "Elton John - Can You Feel the Love Tonight (From \"The Lion King\"/Official Video)", "author_name": "DisneyMusicVEVO"},
 "song-sweet-caroline": {"id": "4F_RCWVoL4s", "title": "Neil Diamond - Sweet Caroline (Audio)", "author_name": "neildiamondVEVO"},
 "song-livin-on-a-prayer": {"id": "lDK9QqIzhwk", "title": "Bon Jovi - Livin' On A Prayer", "author_name": "BonJoviVEVO"},
 "song-i-will-survive": {"id": "6dYWe1c3OyU", "title": "Gloria Gaynor - I Will Survive", "author_name": "GloriaGaynorVEVO"},
 "song-mr-brightside": {"id": "gGdGFtwCNBE", "title": "The Killers - Mr. Brightside (Official Music Video)", "author_name": "TheKillersVEVO"},
 "song-dancing-queen": {"id": "xFrGuyw1V8s", "title": "ABBA - Dancing Queen (Official Music Video)", "author_name": "AbbaVEVO"},
 "song-summer-nights": {"id": "A_J2bcNx3Gw", "title": "Summer Nights (From “Grease”)", "author_name": "John Travolta - Topic"},
 "song-africa": {"id": "FTQbiNvZqaY", "title": "Toto - Africa (Official HD Video)", "author_name": "TotoVEVO"},
 "song-bohemian-rhapsody": {"id": "fJ9rUzIMcZQ", "title": "Queen – Bohemian Rhapsody (Official Video Remastered)", "author_name": "Queen Official"},
 "song-autumn-leaves": {"id": "CpB7-8SGlJ0", "title": "Autumn Leaves", "author_name": "Cannonball Adderley - Topic"},
 "song-all-the-things-you-are": {"id": "ASNSS_G62zw", "title": "All The Things You Are", "author_name": "Ella Fitzgerald - Topic"},
 "song-blue-bossa": {"id": "EUxv3AAaK_Y", "title": "Blue Bossa (Remastered)", "author_name": "Joe Henderson Quintet - Topic"},
 "song-there-will-never-be-another-you": {"id": "rMX1LxBba9g", "title": "There Will Never Be Another You", "author_name": "Chet Baker - Topic"},
 "song-misty": {"id": "UOLEEkYO4MA", "title": "Misty", "author_name": "Erroll Garner - Topic"},
 "song-take-the-a-train": {"id": "r2G1fKYFgVU", "title": "Duke Ellington and His Famous Orchestra - Take the \"A\" Train (Audio)", "author_name": "DukeEllingtonVEVO"},
 "song-so-what": {"id": "zqNTltOGh5c", "title": "Miles Davis - So What (Official Video)", "author_name": "MilesDavisVEVO"},
 "song-stella-by-starlight": {"id": "XGx1HvLV_NQ", "title": "Miles Davis - Stella by Starlight (Official Audio)", "author_name": "MilesDavisVEVO"},
 "song-blue-monk": {"id": "Ww3e1tGvpJ8", "title": "Blue Monk (Album Version)", "author_name": "Thelonious Monk - Topic"},
 "song-almost-blue": {"id": "I5l0jkC71Yk", "title": "Almost Blue", "author_name": "Chet Baker - Topic"},
 "song-amazing-grace": {"id": "LGN64GwVIRM", "title": "Aretha Franklin - Amazing Grace (Official Audio)", "author_name": "Aretha Franklin"},
 "song-when-i-was-your-man": {"id": "ekzHIouo8Q4", "title": "Bruno Mars - When I Was Your Man (Official Music Video)", "author_name": "Bruno Mars"},
 "song-break-my-heart-again": {"id": "HjmBLCbTgDo", "title": "FINNEAS - Break My Heart Again (Official Video)", "author_name": "FINNEAS"},
 "song-can-t-help-falling-in-love": {"id": "vGJTaP6anOU", "title": "Elvis Presley - Can't Help Falling In Love (Official Audio)", "author_name": "ElvisPresleyVEVO"},
 "song-say-you-won-t-let-go": {"id": "KcBhJMc9Ibc", "title": "James Arthur - Say You Won't Let Go (Acoustic Version)", "author_name": "JamesAVEVO"},
 "song-die-for-you": {"id": "uPD0QOGTmMI", "title": "The Weeknd - Die For You", "author_name": "TheWeekndVEVO"},
 "song-all-of-me": {"id": "450p7goxZqg", "title": "John Legend - All of Me (Official Video)", "author_name": "johnlegendVEVO"},
 "song-just-the-way-you-are": {"id": "LjhCEhWiKXk", "title": "Bruno Mars - Just The Way You Are (Official Music Video)", "author_name": "Bruno Mars"},
 "song-november-rain": {"id": "8SbUC-UaAxE", "title": "Guns N' Roses - November Rain", "author_name": "GunsNRosesVEVO"},
 "song-sweet-child-o-mine": {"id": "1w7OgIMMRc4", "title": "Guns N' Roses - Sweet Child O' Mine (Official Music Video)", "author_name": "GunsNRosesVEVO"},
 "song-hotel-california": {"id": "09839DpTctU", "title": "Eagles - Hotel California (Live 1977) (Official Video) [HD]", "author_name": "Eagles"},
 "song-summer-of-69": {"id": "9f06QZCVUHg", "title": "Bryan Adams - Summer Of 69 (Official Music Video)", "author_name": "Bryan Adams"},
 "song-make-you-feel-my-love": {"id": "0put0_a--Ng", "title": "Adele - Make You Feel My Love (Official Video)", "author_name": "XL Recordings"},
 "song-set-fire-to-the-rain": {"id": "a2giXO6eyuI", "title": "Set Fire to the Rain", "author_name": "Adele - Topic"},
 "song-somebody-s-me": {"id": "gv9hrQzU0cA", "title": "Enrique Iglesias - Somebody's Me", "author_name": "EnriqueIglesiasVEVO"},
 "song-still-d-r-e": {"id": "_CL6n0FJZpk", "title": "Dr. Dre - Still D.R.E. ft. Snoop Dogg", "author_name": "DrDreVEVO"},
 "song-25-minutes": {"id": "SIWcOdBtLRw", "title": "Michael Learns To Rock - 25 Minutes [Official Video] (with Lyrics Closed Caption)", "author_name": "Michael Learns To Rock"},
 "song-someday": {"id": "__oCUzwL7i0", "title": "Michael Learns To Rock - Someday [Official Video] (with Lyrics Closed Caption)", "author_name": "Michael Learns To Rock"},
 "song-my-love-mine-all-mine": {"id": "vx4kLgnFexo", "title": "Mitski - My Love Mine All Mine (Official Video)", "author_name": "MitskiVEVO"},
 "song-heart-and-soul": {"id": "JPphPGcjdYM", "title": "Heart and Soul", "author_name": "Larry Clinton & His Orchestra - Topic"},
 "song-hallelujah": {"id": "YrLk4vdY28Q", "title": "Leonard Cohen - Hallelujah (Official Live in London 2008)", "author_name": "LeonardCohenVEVO"},
 "song-imagine": {"id": "YkgkThdzX-8", "title": "IMAGINE. (Ultimate Mix, 2020) - John Lennon & The Plastic Ono Band (with the Flux Fiddlers) HD", "author_name": "johnlennon"},
 "song-happy-birthday-to-you": {"id": "c-v-7JRisLA", "title": "Happy Birthday | Kids Songs | Super Simple Songs", "author_name": "Super Simple Songs - Kids Songs"},
 "song-twinkle-twinkle-little-star": {"id": "yCjJyiqpAuU", "title": "Twinkle Twinkle Little Star | Nursery Rhymes for Kids | Super Simple Songs", "author_name": "Super Simple Songs - Kids Songs"},
 "song-brown-eyed-girl": {"id": "UfmkgQRmmeE", "title": "Van Morrison - Brown Eyed Girl (Official Audio)", "author_name": "VanMorrisonVEVO"},
 "song-three-little-birds": {"id": "HNBCVM4KbUM", "title": "Bob Marley & The Wailers - Three Little Birds (Official Music Video)", "author_name": "BobMarleyVEVO"},
 "song-jingle-bells": {"id": "hLf0-lro8X8", "title": "Frank Sinatra - Jingle Bells (Official Music Video)", "author_name": "FrankSinatraVEVO"},
 "song-hey-jude": {"id": "A_MjCqQoLLA", "title": "The Beatles - The Beatles - Hey Jude (Official Music Video) [Remastered 2015]", "author_name": "TheBeatlesVEVO"},
 "song-autumn-leaves-chet-baker-simplified": {"id": "AFTC1Fg9cXQ", "title": "Autumn Leaves", "author_name": "Chet Baker - Topic"},
 "song-my-funny-valentine-easy-version": {"id": "QuMzUXPEPRM", "title": "My Funny Valentine", "author_name": "Chet Baker - Topic"},
 "song-clocks": {"id": "d020hcWA_Wg", "title": "Coldplay - Clocks (Official Video)", "author_name": "Coldplay"},
 "song-piano-man": {"id": "hRlsu-4BNv8", "title": "Billy Joel - Piano Man (Original Video)", "author_name": "billyjoelVEVO"},
 "song-hello": {"id": "YQHsXMglC9A", "title": "Adele - Hello (Official Music Video)", "author_name": "Adele"},
 "song-counting-stars": {"id": "hT_nvWreIhg", "title": "OneRepublic - Counting Stars", "author_name": "OneRepublicVEVO"},
 "song-comptine-d-un-autre-t": {"id": "znfYwABeSZ0", "title": "Comptine d'un autre été, l'après-midi", "author_name": "Yann Tiersen - Topic"},
 "song-river-flows-in-you": {"id": "7maJOI3QMu0", "title": "Yiruma, (이루마) - River Flows in You", "author_name": "YirumaVEVO"},
 "song-radioactive": {"id": "ktvTqknDobU", "title": "Imagine Dragons - Radioactive", "author_name": "ImagineDragonsVEVO"},
 "song-billie-jean": {"id": "Zi_XLOBDo_Y", "title": "Michael Jackson - Billie Jean (Official Video)", "author_name": "michaeljacksonVEVO"},
 "song-sweet-dreams-are-made-of-this": {"id": "qeMFqkcPYcg", "title": "Eurythmics, Annie Lennox, Dave Stewart - Sweet Dreams (Are Made Of This) (Official Video)", "author_name": "EurythmicsVEVO"},
 "song-fly-me-to-the-moon": {"id": "JYuyWrkwpok", "title": "Frank Sinatra - Fly Me To The Moon (Audio) ft. Count Basie And His Orchestra", "author_name": "FrankSinatraVEVO"},
 "song-take-five": {"id": "-DHuW1h1wHw", "title": "Dave Brubeck, The Dave Brubeck Quartet - Take Five (Audio)", "author_name": "DaveBrubeckVEVO"},
 "song-all-of-me-jazz-standard": {"id": "5J18k5Sx3Dw", "title": "Billie Holiday - All of Me (Official Audio)", "author_name": "BillieHolidayVEVO"},
 "song-summertime": {"id": "2HJCN3upMHE", "title": "Louis Armstrong, Ella Fitzgerald - Summertime (Audio)", "author_name": "EllaFitzgeraldVEVO"},
 "song-satin-doll": {"id": "wQ-n7jhs_K8", "title": "Satin Doll", "author_name": "Duke Ellington - Topic"},
 "song-cantaloupe-island": {"id": "otFVFLtRF_s", "title": "Cantaloupe Island (Remastered 1999/Rudy Van Gelder Edition)", "author_name": "Herbie Hancock - Topic"},
 "song-gymnop-die-no-1": {"id": "EaTjt_iIs2s", "title": "Gymnopédie No. 1", "author_name": "Erik Satie - Topic"},
 "song-prelude-in-c-major-bwv-846": {"id": "gVah1cr3pU0", "title": "Lang Lang – Bach: The Well-Tempered Clavier: Book 1, 1.Prelude C Major, BWV 846", "author_name": "Deutsche Grammophon - DG"},
 "song-the-blue-danube-waltz": {"id": "woWJqKznCSc", "title": "Wiener Philharmoniker, Riccardo Muti - Blue Danube Waltz", "author_name": "WienerPhilVEVO"},
 "song-hungarian-rhapsody-no-2": {"id": "HCRgLae3Ujc", "title": "Liszt: Hungarian Rhapsody No. 2, S. 359/2 (Orch. Doppler/Liszt in D Minor from S. 244/2)", "author_name": "Herbert von Karajan - Topic"},
 "song-while-my-guitar-gently-weeps": {"id": "zOKGcEfSwnY", "title": "The Beatles - While My Guitar Gently Weeps (2018 Mix / Audio)", "author_name": "TheBeatlesVEVO"},
 "song-comfortably-numb": {"id": "7kWl-ZGMwkQ", "title": "Pink Floyd - Comfortably Numb (PULSE Restored & Re-Edited)", "author_name": "Pink Floyd"},
 "song-stairway-to-heaven": {"id": "Ly6ZhQVnVow", "title": "Led Zeppelin - Stairway To Heaven (Live at Earl's Court 1975) [Official Video]", "author_name": "Led Zeppelin"},
 "song-les-champs-elys-es": {"id": "bb-DKKRN4o8", "title": "Joe Dassin - Les Champs-Elysées (Clip officiel)", "author_name": "joedassinVEVO"},
 "song-je-veux": {"id": "0TFNGRYMz1U", "title": "ZAZ - Je veux (Clip officiel)", "author_name": "Zaz Official"},
 "song-papaoutai": {"id": "oiKj0Z_Xnjc", "title": "Stromae - papaoutai (Official Video)", "author_name": "StromaeVEVO"},
 "song-la-vie-en-rose": {"id": "-0KvBnIvTFs", "title": "Edith Piaf - La vie en rose (Audio officiel)", "author_name": "Edith Piaf Officiel"},
 "song-non-je-ne-regrette-rien": {"id": "4r454dad7tc", "title": "Edith Piaf - Non, je ne regrette rien (Audio officiel)", "author_name": "Edith Piaf Officiel"},
 "song-la-bamba": {"id": "0ymdjg9v8zM", "title": "La Bamba", "author_name": "Ritchie Valens - Topic"},
 "song-guantanamera": {"id": "J1VfQVIZKaU", "title": "Guantanamera", "author_name": "Joseito Fernandez - Topic"},
 "song-bailando": {"id": "NUsoVlDFqZg", "title": "Enrique Iglesias - Bailando ft. Descemer Bueno, Gente De Zona", "author_name": "EnriqueIglesiasVEVO"},
 "song-vivir-mi-vida": {"id": "YXnjy5YlDwk", "title": "Marc Anthony - Vivir Mi Vida (Official Video)", "author_name": "marcanthonyVEVO"},
 "song-mas-que-nada": {"id": "hg0XftC43Zo", "title": "Mas, Que Nada!", "author_name": "Jorge Ben Jor - Topic"},
 "song-ai-se-eu-te-pego": {"id": "hcm55lU9knw", "title": "Michel Teló - Ai Se Eu Te Pego -  Video Oficial (Assim você me mata)", "author_name": "Michel Teló"},
 "song-trem-bala": {"id": "sWhy1VcvvgY", "title": "Ana Vilela - Trem-Bala - (Clipe Oficial)", "author_name": "Ana Vilela"},
 "song-tempo-perdido": {"id": "qku-HL1pmYs", "title": "Tempo Perdido", "author_name": "Legiao Urbana - Topic"},
 "song-evid-ncias": {"id": "ePjtnSPFWK8", "title": "Chitãozinho & Xororó - Evidências", "author_name": "CHXVEVO"},
 "song-nel-blu-dipinto-di-blu-volare": {"id": "6jWsIpAbo-8", "title": "Volare (Nel Blu Dipinto Di Blu) (Remastered)", "author_name": "Domenico Modugno - Topic"},
 "song-bella-ciao": {"id": "jEcwLBp2Y80", "title": "Bella ciao (Remastered)", "author_name": "Milva - Topic"},
 "song-l-italiano": {"id": "TYtdYslLY9I", "title": "L'italiano - Toto Cutugno Video Ufficiale", "author_name": "Toto Cutugno"},
 "song-felicit": {"id": "xUj-lfx6vbo", "title": "Al Bano & Romina Power - Felicità (Musikladen 11.03.1982)", "author_name": "AlBanoVEVO"},
 "song-sar-perch-ti-amo": {"id": "IzlY6eehBoE", "title": "Ricchi e Poveri - Sarà perché ti amo (Musicalmente - Ricchi e Poveri, 1981)", "author_name": "RicchiEPoveriVEVO"},
 "song-99-luftballons": {"id": "Fpu5a0Bl8eY", "title": "NENA | 99 Luftballons [1983] [Offizielles HD Musikvideo]", "author_name": "NENA"},
 "song-atemlos-durch-die-nacht": {"id": "haECT-SerHk", "title": "Helene Fischer - Atemlos durch die Nacht", "author_name": "HeleneFischerVEVO"},
 "song-tage-wie-diese": {"id": "j09hpp3AxIE", "title": "Die Toten Hosen // „Tage wie diese\" [Offizielles Musikvideo]", "author_name": "DIE TOTEN HOSEN"},
 "song-auf-uns": {"id": "k9EYjn5f_nE", "title": "Andreas Bourani - Auf uns (Official Video)", "author_name": "Digster Pop Music"},
 "song-stille-nacht-heilige-nacht": {"id": "vKvKMgR8H7k", "title": "Vienna Boys Choir - Stille Nacht (Silent Night)", "author_name": "Wiener Sängerknaben / Vienna Boys Choir (official)"},
 "song-tum-hi-ho": {"id": "WWZxDA81JFk", "title": "Tum Hi Ho Aashiqui 2 Full Video Song | Aditya Roy Kapur, Shraddha Kapoor", "author_name": "T-Series"},
 "song-channa-mereya": {"id": "284Ov7ysmfA", "title": "Channa Mereya Full Video - ADHM | Ranbir Kapoor, Anushka | Arijit Singh | Pritam | Karan Johar", "author_name": "Sony Music India"},
 "song-kesariya": {"id": "BddP6PYo2gs", "title": "Kesariya - Brahmāstra | Ranbir Kapoor, Alia Bhatt | Pritam | Arijit Singh | Amitabh Bhattacharya| 4K", "author_name": "Sony Music India"},
 "song-agar-tum-saath-ho": {"id": "xRb8hxwN5zc", "title": "'AGAR TUM SAATH HO' Full VIDEO song | Tamasha | Ranbir Kapoor, Deepika Padukone | T-Series", "author_name": "T-Series"},
 "song-pal-pal-dil-ke-paas": {"id": "AMuRRXCuy-4", "title": "Blackmail - Pal Pal Dil Ke Paas Tum Rehti Ho - Kishore Kumar", "author_name": "Shemaroo"},
 "song-ue-o-muite-aruk-sukiyaki": {"id": "F284iB65-QU", "title": "Sukiyaki", "author_name": "Kyu Sakamoto - Topic"},
 "song-lemon": {"id": "SX_ViT4Ra7k", "title": "米津玄師  Kenshi Yonezu  - Lemon", "author_name": "Kenshi Yonezu  米津玄師"},
 "song-marigold": {"id": "0xSiBpUdW4E", "title": "あいみょん - マリーゴールド【OFFICIAL MUSIC VIDEO】", "author_name": "あいみょん"},
 "song-plastic-love": {"id": "T_lC2O1oIew", "title": "竹内まりや -  Plastic Love (Official Music Video)", "author_name": "竹内まりや - Mariya Takeuchi Official YouTube Channel"},
 "song-spring-day": {"id": "xEeFrLSkMm8", "title": "BTS (방탄소년단) '봄날 (Spring Day)' Official MV", "author_name": "HYBE LABELS"},
 "song-love-scenario": {"id": "vecSVX1QYbQ", "title": "iKON - ‘사랑을 했다(LOVE SCENARIO)’ M/V", "author_name": "iKON"},
 "song-through-the-night": {"id": "B-4Y_OVBpto", "title": "IU(아이유) - Through the Night(밤편지) (Sketchbook) | KBS WORLD TV 200918", "author_name": "KBS WORLD TV"},
 "song-stay-with-me": {"id": "pcKR0LPwoYs", "title": "[도깨비 OST Part 1] 찬열, 펀치 (CHANYEOL, PUNCH) - Stay With Me MV", "author_name": "STONE MUSIC"},
 "song-eight": {"id": "tJM0yIbg8iQ", "title": "[IU] 'eight' Acoustic Ver. Live Clip", "author_name": "이지금 [IU Official]"},
 "song-the-moon-represents-my-heart-yu-li-ng-d-ibi-o-w-de-x-n": {"id": "IgvDMB5fR-8", "title": "月亮代表我的心", "author_name": "Teresa Teng - Topic"},
 "song-ti-n-m-m": {"id": "5eF8oOWtsk4", "title": "鄧麗君 Teresa Teng テレサ・テン - 甜蜜蜜 (Official Music Video)", "author_name": "TeresaTengVEVO"},
 "song-sunny-day-q-ng-ti-n": {"id": "DYptgVvkVLQ", "title": "周杰倫 Jay Chou【晴天 Sunny Day】-Official Music Video", "author_name": "周杰倫 Jay Chou"},
 "song-fairy-tale-t-ng-hu": {"id": "bBcp_ljCBGU", "title": "光良 Michael Wong【童話】Official Music Video", "author_name": "滾石唱片 ROCK RECORDS"},
 "song-mouse-loves-rice-l-osh-i-d-m": {"id": "zwT8iOwj9Ms", "title": "2011年网络春晚 歌曲《老鼠爱大米》 杨臣刚| CCTV春晚", "author_name": "CCTV春晚"},
 "song-tamally-maak": {"id": "EgmXTmj62ic", "title": "@AmrDiab - Tamally Maak | Official Music Video - HD Version | عمرو دياب - تملي معاك", "author_name": "Mazzika - مزيكا"},
 "song-habibi-ya-nour-el-ein": {"id": "KLJA-srM_yM", "title": "Amr Diab - Nour El Ein | Official Music Video - HD Version | عمرو دياب - نور العين", "author_name": "Mazzika - مزيكا"},
 "song-ya-rayah": {"id": "vBu2OXGWBFI", "title": "Rachid Taha - Ya Rayah", "author_name": "RachidTahaVEVO"},
 "song-lamma-bada-yatathanna": {"id": "AhBeeVYkDe8", "title": "Lamma Bada Yatathanna - Fairuz | لما بدا يتثنى - فيروز", "author_name": "Fairuz"}
};
const SONG_VIDEOS = {
 "Bamboléo": "bamboleo",
 "Creep": "creep",
 "The A Team": "the-a-team",
 "Perfect": "perfect",
 "Viva La Vida": "viva-la-vida",
 "Take Me Home, Country Roads": "country-roads",
 "Linger": "linger",
 "Love Story": "love-story",
 "Let It Be": "let-it-be",
 "Stand By Me": "stand-by-me",
 "Someone Like You": "someone-like-you",
 "No Woman No Cry": "no-woman-no-cry",
 "Don't Stop Believin'": "dont-stop-believin",
 "My Funny Valentine": "my-funny-valentine",
 "Bad Guy": "song-bad-guy",
 "Last Christmas": "song-last-christmas",
 "All I Want for Christmas Is You": "song-all-i-want-for-christmas-is-you",
 "Die With a Smile": "song-die-with-a-smile",
 "Blinding Lights": "song-blinding-lights",
 "Shape of You": "song-shape-of-you",
 "Sweater Weather": "song-sweater-weather",
 "Starboy": "song-starboy",
 "As It Was": "song-as-it-was",
 "Someone You Loved": "song-someone-you-loved",
 "Sunflower": "song-sunflower",
 "One Dance": "song-one-dance",
 "Stay": "song-stay",
 "Believer": "song-believer",
 "I Wanna Be Yours": "song-i-wanna-be-yours",
 "Heat Waves": "song-heat-waves",
 "Yellow": "song-yellow",
 "The Night We Met": "song-the-night-we-met",
 "Closer": "song-closer",
 "Riptide": "song-riptide",
 "Levitating": "song-levitating",
 "Lucid Dreams": "song-lucid-dreams",
 "Photograph": "song-photograph",
 "You Belong With Me": "song-you-belong-with-me",
 "Lover": "song-lover",
 "Shake It Off": "song-shake-it-off",
 "Wildest Dreams": "song-wildest-dreams",
 "Shallow": "song-shallow",
 "Million Reasons": "song-million-reasons",
 "Always Remember Us This Way": "song-always-remember-us-this-way",
 "Have Yourself a Merry Little Christmas": "song-have-yourself-a-merry-little-christmas",
 "Thinking Out Loud": "song-thinking-out-loud",
 "Galway Girl": "song-galway-girl",
 "Drop It Like It's Hot": "song-drop-it-like-it-s-hot",
 "Gin and Juice": "song-gin-and-juice",
 "Young, Wild & Free": "song-young-wild-free",
 "With or Without You": "song-with-or-without-you",
 "I'm Yours": "song-i-m-yours",
 "Despacito": "song-despacito",
 "Let Her Go": "song-let-her-go",
 "A Horse With No Name": "song-a-horse-with-no-name",
 "Knockin' on Heaven's Door": "song-knockin-on-heaven-s-door",
 "Wonderwall": "song-wonderwall",
 "Love Yourself": "song-love-yourself",
 "Count on Me": "song-count-on-me",
 "Zombie": "song-zombie",
 "Hey Soul Sister": "song-hey-soul-sister",
 "Let It Go": "song-let-it-go",
 "Budapest": "song-budapest",
 "Sweet Home Alabama": "song-sweet-home-alabama",
 "Wonderful Tonight": "song-wonderful-tonight",
 "Over the Rainbow": "song-over-the-rainbow",
 "Chasing Cars": "song-chasing-cars",
 "Happy": "song-happy",
 "Banana Pancakes": "song-banana-pancakes",
 "Can You Feel the Love Tonight": "song-can-you-feel-the-love-tonight",
 "Sweet Caroline": "song-sweet-caroline",
 "Livin' on a Prayer": "song-livin-on-a-prayer",
 "I Will Survive": "song-i-will-survive",
 "Mr. Brightside": "song-mr-brightside",
 "Dancing Queen": "song-dancing-queen",
 "Summer Nights": "song-summer-nights",
 "Africa": "song-africa",
 "Bohemian Rhapsody": "song-bohemian-rhapsody",
 "Autumn Leaves": "song-autumn-leaves",
 "All the Things You Are": "song-all-the-things-you-are",
 "Blue Bossa": "song-blue-bossa",
 "There Will Never Be Another You": "song-there-will-never-be-another-you",
 "Misty": "song-misty",
 "Take the A Train": "song-take-the-a-train",
 "So What": "song-so-what",
 "Stella by Starlight": "song-stella-by-starlight",
 "Blue Monk": "song-blue-monk",
 "Almost Blue": "song-almost-blue",
 "Amazing Grace": "song-amazing-grace",
 "When I Was Your Man": "song-when-i-was-your-man",
 "Break My Heart Again": "song-break-my-heart-again",
 "Can't Help Falling in Love": "song-can-t-help-falling-in-love",
 "Say You Won't Let Go": "song-say-you-won-t-let-go",
 "Die for You": "song-die-for-you",
 "All of Me": "song-all-of-me",
 "Just the Way You Are": "song-just-the-way-you-are",
 "November Rain": "song-november-rain",
 "Sweet Child O' Mine": "song-sweet-child-o-mine",
 "Hotel California": "song-hotel-california",
 "Summer of '69": "song-summer-of-69",
 "Make You Feel My Love": "song-make-you-feel-my-love",
 "Set Fire to the Rain": "song-set-fire-to-the-rain",
 "Somebody's Me": "song-somebody-s-me",
 "Still D.R.E.": "song-still-d-r-e",
 "25 Minutes": "song-25-minutes",
 "Someday": "song-someday",
 "My Love Mine All Mine": "song-my-love-mine-all-mine",
 "Heart and Soul": "song-heart-and-soul",
 "Hallelujah": "song-hallelujah",
 "Imagine": "song-imagine",
 "Happy Birthday to You": "song-happy-birthday-to-you",
 "Twinkle Twinkle Little Star": "song-twinkle-twinkle-little-star",
 "Brown Eyed Girl": "song-brown-eyed-girl",
 "Three Little Birds": "song-three-little-birds",
 "Jingle Bells": "song-jingle-bells",
 "Hey Jude": "song-hey-jude",
 "Autumn Leaves (Chet Baker, simplified)": "song-autumn-leaves-chet-baker-simplified",
 "My Funny Valentine (easy version)": "song-my-funny-valentine-easy-version",
 "Clocks": "song-clocks",
 "Piano Man": "song-piano-man",
 "Hello": "song-hello",
 "Counting Stars": "song-counting-stars",
 "Comptine d'un autre été": "song-comptine-d-un-autre-t",
 "River Flows in You": "song-river-flows-in-you",
 "Radioactive": "song-radioactive",
 "Billie Jean": "song-billie-jean",
 "Sweet Dreams (Are Made of This)": "song-sweet-dreams-are-made-of-this",
 "Fly Me to the Moon": "song-fly-me-to-the-moon",
 "Take Five": "song-take-five",
 "All of Me (jazz standard)": "song-all-of-me-jazz-standard",
 "Summertime": "song-summertime",
 "Satin Doll": "song-satin-doll",
 "Cantaloupe Island": "song-cantaloupe-island",
 "Gymnopédie No. 1": "song-gymnop-die-no-1",
 "Prelude in C major, BWV 846": "song-prelude-in-c-major-bwv-846",
 "The Blue Danube (waltz)": "song-the-blue-danube-waltz",
 "Hungarian Rhapsody No. 2": "song-hungarian-rhapsody-no-2",
 "While My Guitar Gently Weeps": "song-while-my-guitar-gently-weeps",
 "Comfortably Numb": "song-comfortably-numb",
 "Stairway to Heaven": "song-stairway-to-heaven",
 "Les Champs-Elysées": "song-les-champs-elys-es",
 "Je veux": "song-je-veux",
 "Papaoutai": "song-papaoutai",
 "La Vie en rose": "song-la-vie-en-rose",
 "Non, je ne regrette rien": "song-non-je-ne-regrette-rien",
 "La Bamba": "song-la-bamba",
 "Guantanamera": "song-guantanamera",
 "Bailando": "song-bailando",
 "Vivir Mi Vida": "song-vivir-mi-vida",
 "Mas Que Nada": "song-mas-que-nada",
 "Ai Se Eu Te Pego": "song-ai-se-eu-te-pego",
 "Trem-Bala": "song-trem-bala",
 "Tempo Perdido": "song-tempo-perdido",
 "Evidências": "song-evid-ncias",
 "Nel blu, dipinto di blu (Volare)": "song-nel-blu-dipinto-di-blu-volare",
 "Bella Ciao": "song-bella-ciao",
 "L'Italiano": "song-l-italiano",
 "Felicità": "song-felicit",
 "Sarà perché ti amo": "song-sar-perch-ti-amo",
 "99 Luftballons": "song-99-luftballons",
 "Atemlos durch die Nacht": "song-atemlos-durch-die-nacht",
 "Tage wie diese": "song-tage-wie-diese",
 "Auf uns": "song-auf-uns",
 "Stille Nacht, heilige Nacht": "song-stille-nacht-heilige-nacht",
 "Tum Hi Ho": "song-tum-hi-ho",
 "Channa Mereya": "song-channa-mereya",
 "Kesariya": "song-kesariya",
 "Agar Tum Saath Ho": "song-agar-tum-saath-ho",
 "Pal Pal Dil Ke Paas": "song-pal-pal-dil-ke-paas",
 "Ue o Muite Arukō (Sukiyaki)": "song-ue-o-muite-aruk-sukiyaki",
 "Lemon": "song-lemon",
 "Marigold": "song-marigold",
 "Plastic Love": "song-plastic-love",
 "Spring Day": "song-spring-day",
 "Love Scenario": "song-love-scenario",
 "Through the Night": "song-through-the-night",
 "Stay With Me": "song-stay-with-me",
 "Eight": "song-eight",
 "The Moon Represents My Heart (Yuèliàng Dàibiǎo Wǒ de Xīn)": "song-the-moon-represents-my-heart-yu-li-ng-d-ibi-o-w-de-x-n",
 "Tián Mì Mì": "song-ti-n-m-m",
 "Sunny Day (Qíng Tiān)": "song-sunny-day-q-ng-ti-n",
 "Fairy Tale (Tóng Huà)": "song-fairy-tale-t-ng-hu",
 "Mouse Loves Rice (Lǎoshǔ Ài Dàmǐ)": "song-mouse-loves-rice-l-osh-i-d-m",
 "Tamally Maak": "song-tamally-maak",
 "Habibi Ya Nour El Ein": "song-habibi-ya-nour-el-ein",
 "Ya Rayah": "song-ya-rayah",
 "Lamma Bada Yatathanna": "song-lamma-bada-yatathanna"
};
export { PEOPLE, VIDEOS, SONG_VIDEOS };
