// Generated from the media research (2026-10-06): freely licensed
// Wikimedia Commons photos (bundled in assets/people/, credited under
// each photo) and YouTube video IDs verified with YouTube's oEmbed
// endpoint (official channels where available).
const PEOPLE = {
 "torres": {
  "person": "Antonio de Torres Jurado (1817–1892)",
  "artist": "Unknown photographer",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Antonio_de_torres_jurado_001.jpg",
  "file": "Antonio de torres jurado 001.jpg",
  "img": "assets/people/torres.webp"
 },
 "torres-guitar": {
  "person": "A guitar by Torres, Museu de la Música de Barcelona",
  "artist": "sguastevi",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Guitarra_d%27Antonio_de_Torres,_MDMB_626,_al_Museu_de_la_M%C3%BAsica_de_Barcelona.jpg",
  "file": "Guitarra d'Antonio de Torres, MDMB 626, al Museu de la Música de Barcelona.jpg",
  "img": "assets/people/torres-guitar.webp"
 },
 "les-paul": {
  "person": "Les Paul",
  "artist": "William P. Gottlieb",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Les_Paul,_ca._Jan._1947_(William_P._Gottlieb_07001).jpg",
  "file": "Les Paul, ca. Jan. 1947 (William P. Gottlieb 07001).jpg",
  "img": "assets/people/les-paul.webp"
 },
 "brian-may": {
  "person": "Brian May",
  "artist": "Gage Skidmore",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Brian_May_(54760284093).jpg",
  "file": "Brian May (54760284093).jpg",
  "img": "assets/people/brian-may.webp"
 },
 "jimmy-page": {
  "person": "Jimmy Page",
  "artist": "Avda",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Jimmy_Page_at_the_Echo_music_award_2013.jpg",
  "file": "Jimmy Page at the Echo music award 2013.jpg",
  "img": "assets/people/jimmy-page.webp"
 },
 "robert-plant": {
  "person": "Robert Plant",
  "artist": "Raph_PH",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:RPlantSavGraceIpswich140324_(5_of_12)_(53589044022)_(cropped).jpg",
  "file": "RPlantSavGraceIpswich140324 (5 of 12) (53589044022) (cropped).jpg",
  "img": "assets/people/robert-plant.webp"
 },
 "don-felder": {
  "person": "Don Felder",
  "artist": "TaurusEmerald",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Don_Felder_Auto_Club_2023.jpg",
  "file": "Don Felder Auto Club 2023.jpg",
  "img": "assets/people/don-felder.webp"
 },
 "joe-walsh": {
  "person": "Joe Walsh",
  "artist": "Derek Russell",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Joe_Walsh_2019.jpg",
  "file": "Joe Walsh 2019.jpg",
  "img": "assets/people/joe-walsh.webp"
 },
 "slash": {
  "person": "Slash (musician)",
  "artist": "Kreepin Deth",
  "license": "CC BY-SA 4.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Slash_live_in_London_2022_(Cropped_-_upright).jpg",
  "file": "Slash live in London 2022 (Cropped - upright).jpg",
  "img": "assets/people/slash.webp"
 },
 "jimi-hendrix": {
  "person": "Jimi Hendrix",
  "artist": "Original photographer unknown",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Jimi_Hendrix_(1967)_(cropped).jpg",
  "file": "Jimi Hendrix (1967) (cropped).jpg",
  "img": "assets/people/jimi-hendrix.webp"
 },
 "django": {
  "person": "Django Reinhardt",
  "artist": "William P. Gottlieb / Adam Cuerden",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Django_Reinhardt_(Gottlieb_07301).jpg",
  "file": "Django Reinhardt (Gottlieb 07301).jpg",
  "img": "assets/people/django.webp"
 },
 "bb-king": {
  "person": "B.B. King",
  "artist": "Marco Tambara / Lightversus",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Bbking.jpg",
  "file": "Bbking.jpg",
  "img": "assets/people/bb-king.webp"
 },
 "eddie-van-halen": {
  "person": "Eddie Van Halen",
  "artist": "Carl Lender",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Eddie_Van_Halen_at_the_New_Haven_Coliseum.jpg",
  "file": "Eddie Van Halen at the New Haven Coliseum.jpg",
  "img": "assets/people/eddie-van-halen.webp"
 },
 "merle-travis": {
  "person": "Merle Travis",
  "artist": "Film screenshot (Sutton Pictures)",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Merle_Travis_in_Five_Minutes_to_Live_(1961).jpg",
  "file": "Merle Travis in Five Minutes to Live (1961).jpg",
  "img": "assets/people/merle-travis.webp"
 },
 "cf-martin": {
  "person": "Christian Frederick Martin (C. F. Martin & Company founder)",
  "artist": "Unknown author",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Christian_Frederick_Martin.jpg",
  "file": "Christian Frederick Martin.jpg",
  "img": "assets/people/cf-martin.webp"
 },
 "segovia": {
  "person": "Andrés Segovia",
  "artist": "Erling Mandelmann",
  "license": "CC BY-SA 3.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Andr%C3%A9s_Segovia_(1963)_by_Erling_Mandelmann.jpg",
  "file": "Andrés Segovia (1963) by Erling Mandelmann.jpg",
  "img": "assets/people/segovia.webp"
 },
 "tarrega": {
  "person": "Francisco Tárrega",
  "artist": "Unknown",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Francisco_tarrega_retrato.jpg",
  "file": "Francisco tarrega retrato.jpg",
  "img": "assets/people/tarrega.webp"
 },
 "paco-de-lucia": {
  "person": "Paco de Lucía",
  "artist": "Cornel Putan",
  "license": "CC BY 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Paco_de_Luc%C3%ADa_4.jpg",
  "file": "Paco de Lucía 4.jpg",
  "img": "assets/people/paco-de-lucia.webp"
 },
 "joao-gilberto": {
  "person": "João Gilberto",
  "artist": "Tuca Vieira from São Paulo, Brazil",
  "license": "CC BY-SA 2.0",
  "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Jo%C3%A3o_Gilberto.jpg",
  "file": "João Gilberto.jpg",
  "img": "assets/people/joao-gilberto.webp"
 },
 "ali-farka-toure": {
  "person": "Ali Farka Touré",
  "artist": "Tagles",
  "license": "Public domain",
  "licenseUrl": null,
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Ali_Farka_Toure.jpg",
  "file": "Ali Farka Toure.jpg",
  "img": "assets/people/ali-farka-toure.webp"
 },
 "prince": {
  "person": "Prince",
  "artist": "Unknown author (1988 promotional photo)",
  "license": "Public domain",
  "licenseUrl": "",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:Prince_promo_picture_(1988;_cropped_and_retouched).png",
  "img": "assets/people/prince.webp"
 },
 "george-harrison": {
  "person": "George Harrison",
  "artist": "John Kelly",
  "license": "Public domain",
  "licenseUrl": "",
  "pageUrl": "https://commons.wikimedia.org/wiki/File:George-wa-portrait.jpg",
  "img": "assets/people/george-harrison.webp"
 }
};
const VIDEOS = {
 "teach-hold": {"id": "C-mt8td1teU", "title": "Holding the Guitar with Your Fretting Hand? | Guitar for Beginners", "author_name": "JustinGuitar", "kind": "teacher"},
 "teach-first-chords": {"id": "jcGSBDZKbFw", "title": "Three Easy and Popular Chords to Get You Playing Songs (G, C, D)  | Beginner Guitar Tips", "author_name": "Guitar Center", "kind": "teacher"},
 "teach-changing": {"id": "xSFHgeJUuIs", "title": "Want Fast & Perfect Chord Changes on Guitar?", "author_name": "JustinGuitar", "kind": "teacher"},
 "teach-finger-strum": {"id": "0YIY52OW5Do", "title": "How to Strum With and Without a Pick", "author_name": "Andy Guitar", "kind": "teacher"},
 "teach-strum-patterns": {"id": "6LmQCdt_ZhQ", "title": "The Most Common Strumming Pattern of All Time! Guitar for Beginners", "author_name": "JustinGuitar", "kind": "teacher"},
 "teach-barre": {"id": "rb0rNvUw46I", "title": "F BARRE CHORD GUITAR  - TOP 5 TIPS!", "author_name": "Andy Guitar", "kind": "teacher"},
 "teach-capo": {"id": "KjU-ga47lXI", "title": "Using a Capo | Beginner Guitar Tips", "author_name": "Guitar Center", "kind": "teacher"},
 "teach-tuning": {"id": "woGj3RsJwv8", "title": "How to Tune an Acoustic Guitar for Beginners | Fender Play | Fender", "author_name": "Fender", "kind": "teacher"},
 "teach-first-chords-em": {"id": "lqcd3jVysXY", "title": "Em chord (JustinGuitar)", "author_name": "JustinGuitar", "kind": "teacher"},
 "fairy-tale-t-ng-hu-live-v2": {"id": "bO_yuRt8pf0", "title": "MAYDAY五月天 ╳ 光良 Michael Wong [ 童話 Fairy Tale ] 5525版 Official Live Video", "author_name": "相信音樂BinMusic", "kind": "live"},
 "sunny-day-q-ng-ti-n-live-v2": {"id": "JKPVRyg01gg", "title": "【周杰倫地表最強演唱會LIVE-晴天】 Jay Chou's The Invincible Concert LIVE (Sunny Day)", "author_name": "周杰倫 Jay Chou", "kind": "live"},
 "stay-with-me-live-v2": {"id": "gczLiXqHR-8", "title": "Punch - Stay With Me (feat. EXO Chanyeol) [Yu Huiyeol's Sketchbook/2018.03.14]", "author_name": "KBS WORLD TV", "kind": "live"},
 "love-scenario-live-v2": {"id": "2BwNheaB1Mw", "title": "LOVE SCENARIO (Band Ver.) - iKON [Seoul Festa 2023 K-POP SUPER LIVE] | KBS WORLD TV 230430", "author_name": "KBS WORLD TV", "kind": "live"},
 "spring-day-live-v2": {"id": "5UB8dL4WcCU", "title": "BTS (방탄소년단) '봄날 (Spring Day)' @ A Butterful Getaway with BTS", "author_name": "BANGTANTV", "kind": "live"},
 "plastic-love-live-v2": {"id": "WpQCCB0Lpik", "title": "竹内まりや - プラスティック・ラブ (feat.山下達郎) [Live Version / 2000@日本武道館]", "author_name": "竹内まりや - Mariya Takeuchi Official YouTube Channel", "kind": "live"},
 "marigold-live-v2": {"id": "FQHHA4SSXtg", "title": "あいみょん – マリーゴールド【AIMYON BUDOKAN -1995-】", "author_name": "あいみょん", "kind": "live"},
 "lemon-live-v2": {"id": "if3sdCLhS1A", "title": "Lemon(檸檬) - 米津玄師 2023 TOUR 空想【中日字幕】", "author_name": "米津玄師", "kind": "live"},
 "nel-blu-dipinto-di-blu-volare-live-v2": {"id": "u99ivDAqwSM", "title": "Domenico Modugno \"Volare (Nel blu, dipinto di blu)\" on The Ed Sullivan Show", "author_name": "The Ed Sullivan Show", "kind": "live"},
 "evid-ncias-live-v2": {"id": "bxo9mtJjvS0", "title": "Chitãozinho & Xororó - Evidências [DVD 50 Anos Ao Vivo no Radio City Music Hall - NY]", "author_name": "Chitãozinho & Xororó", "kind": "live"},
 "papaoutai-live-v2": {"id": "8rDIqYseWP0", "title": "Stromae - Papaoutai (Live on KEXP)", "author_name": "KEXP", "kind": "live"},
 "je-veux-live-v2": {"id": "qIMGuSZbmFI", "title": "ZAZ - Je veux (Live)", "author_name": "Zaz Official", "kind": "live"},
 "something-just-like-this-live-v2": {"id": "4u6bWs-ZG0o", "title": "The Chainsmokers & Coldplay - Something Just Like This (Live at the BRITs)", "author_name": "ChainsmokersVEVO", "kind": "live"},
 "sweet-dreams-are-made-of-this-live-v2": {"id": "cEFKfuI00sk", "title": "Eurythmics, Annie Lennox, Dave Stewart - Sweet Dreams (Are Made of This) (Peacetour Live)", "author_name": "EurythmicsVEVO", "kind": "live"},
 "radioactive-live-v2": {"id": "XkNNOG1sx1o", "title": "Imagine Dragons “Radioactive” on the Howard Stern Show (2015)", "author_name": "The Howard Stern Show", "kind": "live"},
 "counting-stars-live-v2": {"id": "d3OrewC08hk", "title": "OneRepublic - Counting Stars in the Live Lounge", "author_name": "BBCRadio1VEVO", "kind": "live"},
 "clocks-live-v2": {"id": "vKw7yvoZ-Tg", "title": "Coldplay - Clocks (Live at Austin City Limits)", "author_name": "Coldplay", "kind": "live"},
 "brown-eyed-girl-live-v2": {"id": "FLW6JTEK3QQ", "title": "Van Morrison - Brown Eyed Girl (Radio 2 In Concert)", "author_name": "BBC Radio 2", "kind": "live"},
 "my-love-mine-all-mine-live-v2": {"id": "9azlH95iSWg", "title": "Mitski — My Love Mine All Mine | LIVE Performance | SiriusXM", "author_name": "SiriusXM", "kind": "live"},
 "somebody-s-me-live-v2": {"id": "QSGW6_yT3Xk", "title": "Enrique Iglesias - Somebody's Me (Live)", "author_name": "Enrique Iglesias", "kind": "live"},
 "summer-of-69-live-v2": {"id": "HtipPCt317Y", "title": "Bryan Adams - Summer of 69 (Live At Wembley 1996)", "author_name": "BryanAdamsVEVO", "kind": "live"},
 "sweet-child-o-mine-live-v2": {"id": "23LT0E89m1s", "title": "Guns N Roses: Sweet Child O' Mine in Dublin", "author_name": "Guns N' Roses", "kind": "live"},
 "can-t-help-falling-in-love-live-v2": {"id": "ttuVUynl5SU", "title": "Elvis Presley - Can't Help Falling In Love ('68 Comeback Special)", "author_name": "ElvisPresleyVEVO", "kind": "live"},
 "dancing-queen-live-v2": {"id": "k2bBTWvmN-8", "title": "ABBA - Dancing Queen (from ABBA In Concert)", "author_name": "AbbaVEVO", "kind": "live"},
 "mr-brightside-live-v2": {"id": "aIcY7hY_YNE", "title": "The Killers - Mr Brightside in the Live Lounge", "author_name": "BBCRadio1VEVO", "kind": "live"},
 "livin-on-a-prayer-live-v2": {"id": "Ba4bLJnj6MI", "title": "Bon Jovi - Livin’ On A Prayer (Live 8 2005)", "author_name": "Live 8", "kind": "live"},
 "sweet-caroline-live-v2": {"id": "ty1dwBCR6D0", "title": "Neil Diamond - Sweet Caroline (Live At The Greek Theatre / 2012)", "author_name": "neildiamondVEVO", "kind": "live"},
 "banana-pancakes-acoustic-v2": {"id": "S3-sJW0hbqk", "title": "Jack Johnson - \"Banana Pancakes\" (Recorded Live for World Cafe)", "author_name": "World Cafe", "kind": "acoustic"},
 "chasing-cars-live-v2": {"id": "LIdX6Hbfabk", "title": "Snow Patrol - Chasing Cars (Live At Abbey Road / 2006)", "author_name": "SnowPatrolVEVO", "kind": "live"},
 "sweet-home-alabama-live-v2": {"id": "x0njSOZ5M3w", "title": "Lynyrd Skynyrd - Sweet Home Alabama - Live At The Florida Theatre / 2015", "author_name": "LynyrdSkynyrdVEVO", "kind": "live"},
 "hey-soul-sister-acoustic-v2": {"id": "A-7XPCNrD5Y", "title": "Train 'Hey, Soul Sister' Billboard Live Acoustic Studio Session", "author_name": "Billboard", "kind": "acoustic"},
 "zombie-live-v2": {"id": "bG5gqx1953s", "title": "The Cranberries - Zombie (Live At The Astoria, London, 1994)", "author_name": "TheCranberriesVEVO", "kind": "live"},
 "love-yourself-live-v2": {"id": "5V_FQa363Y0", "title": "Justin Bieber - 'Love Yourself' (Live At Jingle Bell Ball 2015)", "author_name": "Capital", "kind": "live"},
 "wonderwall-acoustic-v2": {"id": "DL0auwO0bWE", "title": "Noel Gallagher “Wonderwall” Live on the Stern Show (1997)", "author_name": "The Howard Stern Show", "kind": "acoustic"},
 "knockin-on-heaven-s-door-acoustic-v2": {"id": "cJpB_AEZf6U", "title": "Bob Dylan - Knockin' On Heaven's Door (MTV Unplugged)", "author_name": "BobDylanVEVO", "kind": "acoustic"},
 "a-horse-with-no-name-live-v2": {"id": "Xxh9Da_EJB4", "title": "America - A Horse With No Name (America In Concert, May 24,1973)", "author_name": "America", "kind": "live"},
 "stand-by-me-live-v2": {"id": "jnDwrb3zaHE", "title": "Ben E. King / All Star Band - Stand By Me (The Prince's Trust Rock Gala 1987)", "author_name": "King's Trust Music", "kind": "live"},
 "let-her-go-acoustic-v2": {"id": "aPQCyQ5h4Dk", "title": "Passenger - Let Her Go - Live at Spotify Amsterdam", "author_name": "Sony Music Netherlands", "kind": "acoustic"},
 "i-m-yours-live-v2": {"id": "8mCCMhuKEYw", "title": "Jason Mraz - I'm Yours (Live in London)", "author_name": "Jason Mraz", "kind": "live"},
 "with-or-without-you-live-v2": {"id": "6DeDzsCGbsQ", "title": "U2 - With Or Without You | U2 At The BBC", "author_name": "BBC Music", "kind": "live"},
 "galway-girl-acoustic-v2": {"id": "ICb4JuJ4C9Y", "title": "Ed Sheeran - Galway Girl (Acoustic) (Radio X Live Session)", "author_name": "Radio X", "kind": "acoustic"},
 "thinking-out-loud-acoustic-v2": {"id": "f6Cswdm601A", "title": "Ed Sheeran - Thinking Out Loud (x Acoustic Session)", "author_name": "Ed Sheeran", "kind": "acoustic"},
 "shallow-live-v2": {"id": "JPJjwHAIny4", "title": "Lady Gaga, Bradley Cooper - Shallow (From A Star Is Born/Live From The Oscars)", "author_name": "LadyGagaVEVO", "kind": "live"},
 "wildest-dreams-acoustic-v2": {"id": "OGDkg3QiJmk", "title": "Taylor Performs \"Wildest Dreams\" at The GRAMMY Museum", "author_name": "Taylor Swift", "kind": "acoustic"},
 "shake-it-off-acoustic-v2": {"id": "P8ZnjqbOuyc", "title": "Taylor Swift - Shake It Off (in the Live Lounge)", "author_name": "BBCRadio1VEVO", "kind": "acoustic"},
 "lover-acoustic-v2": {"id": "G4I6PhHbH7o", "title": "Taylor Swift - Lover in the Live Lounge", "author_name": "BBCRadio1VEVO", "kind": "acoustic"},
 "photograph-acoustic-v2": {"id": "p9VazLLwzvM", "title": "Ed Sheeran - Photograph (x Acoustic Sessions 2014)", "author_name": "Ed Sheeran", "kind": "acoustic"},
 "riptide-acoustic-v2": {"id": "sqlyIlpV-eA", "title": "Vance Joy - Riptide [Acoustic]", "author_name": "Vance Joy", "kind": "acoustic"},
 "the-night-we-met-live-v2": {"id": "td_CYmQujd0", "title": "Lord Huron - The Night We Met (Live on KEXP)", "author_name": "KEXP", "kind": "live"},
 "yellow-acoustic-v2": {"id": "WxCa5xwdGGw", "title": "Chris Martin Performs Coldplay’s “Yellow” on the Stern Show (2011)", "author_name": "The Howard Stern Show", "kind": "acoustic"},
 "heat-waves-acoustic-v2": {"id": "EFVNzgKRHak", "title": "Glass Animals - Heat Waves (Stripped Back)", "author_name": "Glass Animals", "kind": "acoustic"},
 "i-wanna-be-yours-acoustic-v2": {"id": "7i2gb3dJ6ik", "title": "Arctic Monkeys - I Wanna Be Yours - Session Acoustique OÜI FM", "author_name": "Oüi FM", "kind": "acoustic"},
 "believer-acoustic-v2": {"id": "0qxPqpwzyTE", "title": "Imagine Dragons – Believer 1Live Session", "author_name": "Digster On Stage", "kind": "acoustic"},
 "perfect-acoustic-v2": {"id": "qyKE5FAdnPo", "title": "Ed Sheeran - 'Perfect' (Exclusive Live Session For Global's 'Make Some Noise')", "author_name": "Capital", "kind": "acoustic"},
 "one-dance-live-v2": {"id": "vcer12OFU2g", "title": "Drake - One Dance (Live On SNL) ft. Wizkid, Kyla", "author_name": "DrakeVEVO", "kind": "live"},
 "someone-you-loved-acoustic-v2": {"id": "sDC2BXQNAiM", "title": "Lewis Capaldi - Someone You Loved (Live - Acoustic Room/LADbible)", "author_name": "LewisCapaldiVEVO", "kind": "acoustic"},
 "as-it-was-acoustic-v2": {"id": "VaF92M2dKmQ", "title": "Harry Styles - As It Was in the Live Lounge", "author_name": "BBCRadio1VEVO", "kind": "acoustic"},
 "sweater-weather-acoustic-v2": {"id": "zufL0hntYd0", "title": "The Neighbourhood \"Sweater Weather\" Live Acoustic", "author_name": "ALT 98.7 FM", "kind": "acoustic"},
 "shape-of-you-live-v2": {"id": "Svtr-p4mrQ8", "title": "Ed Sheeran - Shape of You (The Biggest Weekend)", "author_name": "BBC Radio 1", "kind": "live"},
 "die-with-a-smile-live-v2": {"id": "fnPxkuFIA48", "title": "Lady Gaga, Bruno Mars - Die With A Smile (Live in Las Vegas)", "author_name": "Bruno Mars", "kind": "live"},
 "love-story-acoustic-v2": {"id": "cT50TGIBSDU", "title": "Taylor Swift - Love Story in the Live Lounge", "author_name": "BBCRadio1VEVO", "kind": "acoustic"},
 "bambol-o-live-v2": {"id": "659fYhZcmKk", "title": "Gipsy Kings - Bamboléo (Live US Tour '90)", "author_name": "gipsykingsVEVO", "kind": "live"},
 "while-my-guitar-gently-weeps-official-v2": {"id": "VJDJs9dumZI", "title": "The Beatles - The Beatles - While My Guitar Gently Weeps (Official Music Video) [Love Version]", "author_name": "TheBeatlesVEVO"},
 "volare-nel-blu-dipinto-di-blu-live-v2": {"id": "u99ivDAqwSM", "title": "Domenico Modugno \"Volare (Nel blu, dipinto di blu)\" on The Ed Sullivan Show", "author_name": "The Ed Sullivan Show", "kind": "live"},
 "tadhana-live-v2": {"id": "AC95_yd2Yx8", "title": "UP DHARMA DOWN – Tadhana (MYX Live! Performance)", "author_name": "All Music MYX", "kind": "live"},
 "anak-live-v2": {"id": "q0TF_JSEHt0", "title": "FREDDIE AGUILAR – Anak (MYX Live! Performance)", "author_name": "All Music MYX", "kind": "live"},
 "like-a-star-acoustic-v2": {"id": "af4TK7G8q3s", "title": "Corinne Bailey Rae - Like A Star (Live on KCRW)", "author_name": "KCRW", "kind": "acoustic"},
 "bubbly-acoustic-v2": {"id": "gMPS5Uj1x54", "title": "Colbie Caillat - Bubbly (AOL Sessions)", "author_name": "ColbieCaillatVEVO", "kind": "acoustic"},
 "i-m-like-a-bird-acoustic-v2": {"id": "ByrvpWC9_uY", "title": "Nelly Furtado - I'm Like A Bird (Walmart Soundcheck)", "author_name": "NellyFurtadoVEVO", "kind": "acoustic"},
 "pata-pata-live-v2": {"id": "lNeP3hrm__k", "title": "Miriam Makeba - Pata Pata (Live on The Ed Sullivan Show 1967)", "author_name": "Miriam Makeba Official Channel", "kind": "live"},
 "before-he-cheats-acoustic-v2": {"id": "HgBqbUp4Hfw", "title": "Carrie Underwood Performs “Before He Cheats” 🎶VH1 Unplugged | CMT", "author_name": "CMT", "kind": "acoustic"},
 "take-on-me-live-v2": {"id": "IHDCMQjNimg", "title": "a-ha - Take On Me (Radio 2 In Concert)", "author_name": "BBC Radio 2", "kind": "live"},
 "no-surprises-live-v2": {"id": "yWC7JGWCTe4", "title": "Radiohead - No Surprises | Later... with Jools Holland (1997)", "author_name": "BBC Music", "kind": "live"},
 "karma-police-live-v2": {"id": "uEk_mtJ_ssM", "title": "Radiohead - Karma Police (Glastonbury 1997)", "author_name": "BBC Music", "kind": "live"},
 "blank-space-acoustic-v2": {"id": "p1Zt47V3pPw", "title": "Taylor performs \"Blank Space\" at The GRAMMY Museum", "author_name": "Taylor Swift", "kind": "acoustic"},
 "a-cha-acoustic-v2": {"id": "dpCIVTPH3KI", "title": "Khaled \"Aïcha\" live acoustique #PlanèteRap", "author_name": "SkyrockFM", "kind": "acoustic"},
 "lose-control-acoustic-v2": {"id": "OhWmM2dRDV0", "title": "Teddy Swims - Lose Control (NZ Live Acoustic Session)", "author_name": "Warner Music New Zealand", "kind": "acoustic"},
 "tennessee-whiskey-live-v2": {"id": "IBLruNfUqUs", "title": "Chris Stapleton - Tennessee Whiskey (Austin City Limits Performance)", "author_name": "ChrisStapletonVEVO", "kind": "live"},
 "drown-live-v2": {"id": "tDf7SBRmrvE", "title": "Bring Me The Horizon - Drown (Live from Maida Vale)", "author_name": "BMTHOfficialVEVO", "kind": "live"},
 "the-sound-of-silence-live-v2": {"id": "Bk7RVw3I8eg", "title": "Disturbed \"The Sound Of Silence\" 03/28/16 | CONAN on TBS", "author_name": "Team Coco", "kind": "live"},
 "snuff-acoustic-v2": {"id": "QBK6xymmKHM", "title": "Corey Taylor - Snuff (Acoustic)", "author_name": "Corey Taylor", "kind": "acoustic"},
 "what-i-ve-done-live-v2": {"id": "_c1w056MItU", "title": "What I've Done [Official Live in Red Square 2011] - Linkin Park", "author_name": "Linkin Park", "kind": "live"},
 "numb-live-v2": {"id": "7i4s-NXfkPk", "title": "Numb (Live) - Linkin Park", "author_name": "Linkin Park", "kind": "live"},
 "in-the-end-live-v2": {"id": "pQto8npSUC0", "title": "Linkin Park - In the End (Live In Texas)", "author_name": "Linkin Park", "kind": "live"},
 "fear-of-the-dark-live-v2": {"id": "2VgOjY-TPUo", "title": "Iron Maiden - Fear Of The Dark (The Book Of Souls: Live Chapter)", "author_name": "Iron Maiden", "kind": "live"},
 "the-trooper-live-v2": {"id": "ogsv6T_Pg3k", "title": "Iron Maiden - The Trooper (The Book Of Souls: Live Chapter)", "author_name": "Iron Maiden", "kind": "live"},
 "run-to-the-hills-live-v2": {"id": "bEjGuDcDJjU", "title": "Iron Maiden - Run To The Hills (Live from the Legacy Of The Beast Tour)", "author_name": "Iron Maiden", "kind": "live"},
 "breaking-the-law-live-v2": {"id": "O4ujW3oe_BQ", "title": "Judas Priest - Breaking the Law (from Epitaph)", "author_name": "JudasPriestVEVO", "kind": "live"},
 "crazy-train-live-v2": {"id": "8lD5bfqzr6E", "title": "Ozzy Osbourne - Crazy Train (Live)", "author_name": "OzzyOsbourneVEVO", "kind": "live"},
 "iron-man-live-v2": {"id": "7-thChxjcVw", "title": "BLACK SABBATH - \"Iron Man\" from The End (Live Video)", "author_name": "Black Sabbath", "kind": "live"},
 "paranoid-live-v2": {"id": "cen1SvpTsYk", "title": "BLACK SABBATH - \"Paranoid\" Birmingham 2012 (Live Video)", "author_name": "Black Sabbath", "kind": "live"},
 "wherever-i-may-roam-live-v2": {"id": "4U7aF6h_iwA", "title": "Metallica: Wherever I May Roam (Denver, CO - June 7, 2017)", "author_name": "Metallica", "kind": "live"},
 "seek-destroy-live-v2": {"id": "NJzoBmVPeYw", "title": "Metallica: Seek & Destroy (Québec City, Québec - October 31, 2009) [Quebec Magnetic]", "author_name": "Metallica", "kind": "live"},
 "fuel-live-v2": {"id": "9ntSDjbkvoM", "title": "Metallica: Fuel (Gothenburg, Sweden - June 16, 2023)", "author_name": "Metallica", "kind": "live"},
 "fade-to-black-live-v2": {"id": "A-4K4SX0m70", "title": "Metallica: Fade to Black (Toronto, Canada - November 29, 2016)", "author_name": "Metallica", "kind": "live"},
 "sad-but-true-live-v2": {"id": "xROxlIu__Fs", "title": "Metallica: Sad But True (Moscow, Russia - July 21, 2019)", "author_name": "Metallica", "kind": "live"},
 "whiskey-in-the-jar-live-v2": {"id": "9MNdOCQYOL8", "title": "Metallica: Whiskey in the Jar (Slane Castle - Meath, Ireland - June 8, 2019)", "author_name": "Metallica", "kind": "live"},
 "the-unforgiven-acoustic-v2": {"id": "eZ_nVxG26-E", "title": "Metallica: The Unforgiven (San Francisco, CA - November 3, 2018)", "author_name": "Metallica", "kind": "acoustic"},
 "for-whom-the-bell-tolls-live-v2": {"id": "HNybmS3xNAQ", "title": "Metallica - For Whom the Bell Tolls (Live in Mexico City) [Orgullo, Pasión, y Gloria]", "author_name": "Metallica", "kind": "live"},
 "one-live-v2": {"id": "r3hCgDg4XAA", "title": "Metallica: One (Slane Castle - Meath, Ireland - June 8, 2019)", "author_name": "Metallica", "kind": "live"},
 "master-of-puppets-live-v2": {"id": "G9kz-tag04U", "title": "Metallica: Master of Puppets (Manchester, England - June 18, 2019)", "author_name": "Metallica", "kind": "live"},
 "nothing-else-matters-live-v2": {"id": "OMguFafuqrg", "title": "Metallica: Nothing Else Matters (Moscow, Russia - July 21, 2019)", "author_name": "Metallica", "kind": "live"},
 "enter-sandman-acoustic-v2": {"id": "hxTC30Q5l44", "title": "Metallica: Enter Sandman (Bridge School Benefit, Mountain View, CA - October 22, 2016)", "author_name": "Metallica", "kind": "acoustic"},
 "something-just-like-this": {"id": "FM7MFYoylVs", "title": "The Chainsmokers & Coldplay - Something Just Like This (Official Lyric Video)", "author_name": "ChainsmokersVEVO"},
 "les-paul": {
  "id": "FfkPaDmik10",
  "title": "Les Paul tours his Mahwah recording studio from an outtake of his documentary ‘Chasing Sound.’",
  "author_name": "Les Paul Official"
 },
 "brian-may-red-special": {
  "id": "vrz7nlkSt4k",
  "title": "Queen: The Guitar Solo (Episode 38)",
  "author_name": "Queen Official"
 },
 "stairway": {
  "id": "Ly6ZhQVnVow",
  "title": "Led Zeppelin - Stairway To Heaven (Live at Earl's Court 1975) [Official Video]",
  "author_name": "Led Zeppelin"
 },
 "hotel-california": {
  "id": "09839DpTctU",
  "title": "Eagles - Hotel California (Live 1977) (Official Video) [HD]",
  "author_name": "Eagles"
 },
 "november-rain": {
  "id": "8SbUC-UaAxE",
  "title": "Guns N' Roses - November Rain",
  "author_name": "GunsNRosesVEVO"
 },
 "segovia": {
  "id": "bcdS2hbpZcY",
  "title": "Andrés Segovia: Bach - Gavotte from 4th Lute Suite for guitar",
  "author_name": "Allegro Films"
 },
 "romance": {
  "id": "hhZjBd7l6HA",
  "title": "Alexandr Sokolkin plays Romance on Guitar | Siccas Media",
  "author_name": "SiccasGuitars"
 },
 "recuerdos": {
  "id": "fwjX-m4LkYk",
  "title": "Ana Vidovic plays Recuerdos de la Alhambra by Francisco Tárrega on a Jim Redgate classical guitar",
  "author_name": "SiccasGuitars"
 },
 "flamenco": {
  "id": "GayHfFTWdX0",
  "title": "Paco de Lucía | Live at Liège Guitar Festival | 1983",
  "author_name": "Qwest TV"
 },
 "bossa-nova": {
  "id": "Y0a0QuLEC8A",
  "title": "Chega de Saudade",
  "author_name": "João Gilberto - Topic"
 },
 "godfather-tremolo": {
  "id": "xFCYBWQlgqE",
  "title": "\"The Godfather\" for guitar (with a little tremolo)",
  "author_name": "Philip Glaser"
 },
 "slack-key": {
  "id": "rFxrfbQGTwY",
  "title": "Legend and Legacy: Hawaiian Slack-Key Guitar with Ledward Kaapana",
  "author_name": "Smithsonian Folklife"
 },
 "ali-farka-toure": {
  "id": "4mnAUe4c08o",
  "title": "Ali Farka Touré - Savane (Live at Bozar)",
  "author_name": "Ali Farka Touré"
 },
 "how-guitar-made": {
  "id": "PtsFibqgGzo",
  "title": "See How the D-28 is Handmade",
  "author_name": "Martin Guitar"
 },
 "prince-wmggw": {
  "id": "6SFNW5F8K9Y",
  "title": "Prince, Tom Petty, Steve Winwood, & More \"While My Guitar Gently Weeps\" | Rock Hall 2004 Induction",
  "author_name": "Rock & Roll Hall of Fame"
 },
 "creep": {"id": "XFkzRNyygfk", "title": "Radiohead - Creep", "author_name": "Radiohead"},
 "ed-sheeran-looping": {"id": "Q2CW9TZ81wo", "title": "Ed Sheeran: Tiny Desk Concert", "author_name": "NPR Music"},
 "the-a-team": {"id": "xADSSBs34is", "title": "Ed Sheeran - The A Team (Acoustic Boat Sessions)", "author_name": "Ed Sheeran"},
 "perfect": {"id": "9vDIzVuDzTs", "title": "Perfect (Acoustic)", "author_name": "Ed Sheeran - Topic"},
 "viva-la-vida": {"id": "vUnWFsc5WBU", "title": "Chris Martin “Viva la Vida” (Acoustic) on the Howard Stern Show (2016)", "author_name": "The Howard Stern Show"},
 "country-roads": {"id": "IUmnTfsY3hI", "title": "John Denver - Take Me Home, Country Roads (from The Wildlife Concert)", "author_name": "JohnDenverVEVO"},
 "linger": {"id": "sDK0xdiHBcQ", "title": "The Cranberries - Linger (Acoustic Version)", "author_name": "TheCranberriesVEVO"},
 "love-story": {"id": "8xg3vE8Ie_E", "title": "Taylor Swift - Love Story", "author_name": "Taylor Swift"},
 "let-it-be": {"id": "CGj85pVzRJs", "title": "The Beatles - Let It Be (Official Music Video) [Remastered 2015]", "author_name": "TheBeatlesVEVO"},
 "stand-by-me": {"id": "UiTwbwxbG2U", "title": "Stand by Me (Remastered 2015)", "author_name": "Ben E. King - Topic"},
 "someone-like-you": {"id": "NAc83CF8Ejk", "title": "Adele - Someone Like You (Live in Her Home)", "author_name": "Adele"},
 "no-woman-no-cry": {"id": "mZ6VezKMoRY", "title": "Bob Marley & The Wailers - No Woman, No Cry (Live At The Rainbow 4th June 1977)", "author_name": "BobMarleyVEVO"},
 "dont-stop-believin": {"id": "VcjzHMhBtf0", "title": "Journey - Don't Stop Believin' (Escape Tour 1981: Live In Houston)", "author_name": "journeyVEVO"},
 "my-funny-valentine": {"id": "tczRmxcEoow", "title": "Chet Baker - My Funny Valentine (Remastered 2004)", "author_name": "Chet Baker - Topic"},
 "jazz-loop": {"id": "otFVFLtRF_s", "title": "Herbie Hancock - Cantaloupe Island (Remastered 1999)", "author_name": "Herbie Hancock - Topic"},
 "bamboleo": {"id": "7qbEt_lSib4", "title": "Gipsy Kings - Bamboléo (Official Video)", "author_name": "gipsykingsVEVO"},
 "song-bad-guy": {"id": "DyDfgMOUjCI", "title": "Billie Eilish - bad guy", "author_name": "BillieEilishVEVO"},
 "song-last-christmas": {"id": "E8gmARGvPlI", "title": "Wham! - Last Christmas (Official Video)", "author_name": "WhamVEVO"},
 "song-all-i-want-for-christmas-is-you": {"id": "aAkMkVFwAoo", "title": "Mariah Carey - All I Want for Christmas Is You (Make My Wish Come True Edition)", "author_name": "MariahCareyVEVO"},
 "song-die-with-a-smile": {"id": "kPa7bsKwL-c", "title": "Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-blinding-lights": {"id": "4NRXx6U8ABQ", "title": "The Weeknd - Blinding Lights (Official Video)", "author_name": "TheWeekndVEVO"},
 "song-shape-of-you": {"id": "JGwWNGJdvx8", "title": "Ed Sheeran - Shape of You (Official Music Video)", "author_name": "Ed Sheeran"},
 "song-sweater-weather": {"id": "GCdwKhTtNNw", "title": "The Neighbourhood - Sweater Weather (Official Video)", "author_name": "TheNeighbourhoodVEVO"},
 "song-starboy": {"id": "34Na4j8AVgA", "title": "The Weeknd - Starboy ft. Daft Punk (Official Video) ft. Daft Punk", "author_name": "TheWeekndVEVO"},
 "song-as-it-was": {"id": "H5v3kku4y6Q", "title": "Harry Styles - As It Was (Official Video)", "author_name": "HarryStylesVEVO"},
 "song-someone-you-loved": {"id": "zABLecsR5UE", "title": "Lewis Capaldi - Someone You Loved", "author_name": "LewisCapaldiVEVO"},
 "song-sunflower": {"id": "ApXoWvfEYVU", "title": "Post Malone, Swae Lee - Sunflower (Spider-Man: Into the Spider-Verse)", "author_name": "PostMaloneVEVO"},
 "song-one-dance": {"id": "5LFB3qdmZBM", "title": "One Dance", "author_name": "Drake - Topic"},
 "song-stay": {"id": "kTJczUoc26U", "title": "The Kid LAROI, Justin Bieber - STAY (Official Video)", "author_name": "TheKidLAROIVEVO"},
 "song-believer": {"id": "7wtfhZwyrcc", "title": "Imagine Dragons - Believer (Official Music Video)", "author_name": "ImagineDragonsVEVO"},
 "song-i-wanna-be-yours": {"id": "nyuo9-OjNNg", "title": "I Wanna Be Yours", "author_name": "Arctic Monkeys - Topic"},
 "song-heat-waves": {"id": "mRD0-GxqHVo", "title": "Glass Animals - Heat Waves (Official Video)", "author_name": "GlassAnimalsVEVO"},
 "song-yellow": {"id": "yKNxeF4KMsY", "title": "Coldplay - Yellow (Official Video)", "author_name": "Coldplay"},
 "song-the-night-we-met": {"id": "KtlgYxa6BMU", "title": "Lord Huron - The Night We Met (Official Audio)", "author_name": "Lord Huron"},
 "song-closer": {"id": "0zGcUoRlhmw", "title": "The Chainsmokers - Closer (Official Video) ft. Halsey", "author_name": "ChainsmokersVEVO"},
 "song-riptide": {"id": "uJ_1HMAGb4k", "title": "Vance Joy - 'Riptide' Official Video", "author_name": "Mushroom"},
 "song-levitating": {"id": "TUVcZfQe-Kw", "title": "Dua Lipa - Levitating Featuring DaBaby (Official Music Video)", "author_name": "Dua Lipa"},
 "song-lucid-dreams": {"id": "mzB1VGEGcSU", "title": "Juice WRLD - Lucid Dreams (Official Music Video)", "author_name": "Lyrical Lemonade"},
 "song-photograph": {"id": "nSDgHBxUbVQ", "title": "Ed Sheeran - Photograph (Official Music Video)", "author_name": "Ed Sheeran"},
 "song-you-belong-with-me": {"id": "VuNIsY6JdUw", "title": "Taylor Swift - You Belong With Me", "author_name": "Taylor Swift"},
 "song-lover": {"id": "-BjZmE2gtdo", "title": "Taylor Swift - Lover (Official Music Video)", "author_name": "Taylor Swift"},
 "song-shake-it-off": {"id": "nfWlot6h_JM", "title": "Taylor Swift - Shake It Off", "author_name": "Taylor Swift"},
 "song-wildest-dreams": {"id": "IdneKLhsWOQ", "title": "Taylor Swift - Wildest Dreams", "author_name": "Taylor Swift"},
 "song-shallow": {"id": "bo_efYhYU2A", "title": "Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-million-reasons": {"id": "en2D_5TzXCA", "title": "Lady Gaga - Million Reasons (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-always-remember-us-this-way": {"id": "5vheNbQlsyU", "title": "Lady Gaga - Always Remember Us This Way (from A Star Is Born) (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-have-yourself-a-merry-little-christmas": {"id": "0vibMVTvaW0", "title": "Have Yourself A Merry Little Christmas", "author_name": "Judy Garland - Topic"},
 "song-thinking-out-loud": {"id": "lp-EO5I60KA", "title": "Ed Sheeran - Thinking Out Loud (Official Music Video)", "author_name": "Ed Sheeran"},
 "song-galway-girl": {"id": "87gWaABqGYs", "title": "Ed Sheeran - Galway Girl [Official Music Video]", "author_name": "Ed Sheeran"},
 "song-drop-it-like-it-s-hot": {"id": "GtUVQei3nX4", "title": "Snoop Dogg - Drop It Like It's Hot (Official Music Video) ft. Pharrell Williams", "author_name": "SnoopDoggVEVO"},
 "song-gin-and-juice": {"id": "fWCZse1iwE0", "title": "Snoop Dogg - Gin And Juice", "author_name": "SnoopDoggVEVO"},
 "song-young-wild-free": {"id": "Wa5B22KAkEk", "title": "Snoop Dogg & Wiz Khalifa - Young, Wild and Free ft. Bruno Mars [Official Video]", "author_name": "Wiz Khalifa"},
 "song-with-or-without-you": {"id": "ujNeHIo7oTE", "title": "U2 - With Or Without You (Official Music Video)", "author_name": "U2VEVO"},
 "song-i-m-yours": {"id": "EkHTsc9PU2A", "title": "Jason Mraz - I'm Yours (Official Video) [4K Remaster]", "author_name": "Jason Mraz"},
 "song-despacito": {"id": "kJQP7kiw5Fk", "title": "Luis Fonsi - Despacito ft. Daddy Yankee", "author_name": "LuisFonsiVEVO"},
 "song-let-her-go": {"id": "RBumgq5yVrA", "title": "Passenger | Let Her Go (Official Video)", "author_name": "Passenger"},
 "song-a-horse-with-no-name": {"id": "na47wMFfQCo", "title": "America - A Horse With No Name (Official Audio)", "author_name": "RHINO"},
 "song-knockin-on-heaven-s-door": {"id": "rm9coqlk8fY", "title": "Bob Dylan - Knockin' On Heaven's Door (Official Audio)", "author_name": "BobDylanVEVO"},
 "song-wonderwall": {"id": "bx1Bh8ZvH84", "title": "Oasis - Wonderwall (Official Video)", "author_name": "OasisVEVO"},
 "song-love-yourself": {"id": "oyEuk8j8imI", "title": "Justin Bieber - Love Yourself (PURPOSE : The Movement)", "author_name": "JustinBieberVEVO"},
 "song-count-on-me": {"id": "6k8cpUkKK4c", "title": "Bruno Mars - Count on Me (Official Lyric Video)", "author_name": "Bruno Mars"},
 "song-zombie": {"id": "R5SwRvAbpe8", "title": "Zombie (Acoustic Version)", "author_name": "The Cranberries - Topic"},
 "song-hey-soul-sister": {"id": "kVpv8-5XWOI", "title": "Train - Hey, Soul Sister (Official Video)", "author_name": "TrainVEVO"},
 "song-let-it-go": {"id": "YVVTZgwYwVo", "title": "Idina Menzel - Let It Go (from Frozen) (Official Video)", "author_name": "DisneyMusicVEVO"},
 "song-budapest": {"id": "f7raiIQ70iA", "title": "George Ezra - \"Budapest\" (Last.fm Sessions)", "author_name": "Last.fm"},
 "song-sweet-home-alabama": {"id": "-35W_FWCT9Q", "title": "Lynyrd Skynyrd - Sweet Home Alabama (Audio)", "author_name": "LynyrdSkynyrdVEVO"},
 "song-wonderful-tonight": {"id": "UprwkbzUX6g", "title": "Eric Clapton - Wonderful Tonight [Official Live]", "author_name": "Eric Clapton"},
 "song-over-the-rainbow": {"id": "V1bFr2SWP1I", "title": "OFFICIAL Somewhere over the Rainbow - Israel \"IZ\" Kamakawiwoʻole", "author_name": "Mountain Apple Company Inc"},
 "song-chasing-cars": {"id": "GemKqzILV4w", "title": "Snow Patrol - Chasing Cars (Official Video)", "author_name": "SnowPatrolVEVO"},
 "song-happy": {"id": "ZbZSe6N_BXs", "title": "Pharrell Williams - Happy (Official Video)", "author_name": "PharrellWilliamsVEVO"},
 "song-banana-pancakes": {"id": "YdgoG8hTMUw", "title": "Banana Pancakes", "author_name": "Jack Johnson - Topic"},
 "song-can-you-feel-the-love-tonight": {"id": "KjgWWjkNbhU", "title": "Elton John - Can You Feel the Love Tonight (From \"The Lion King\"/Official Video)", "author_name": "DisneyMusicVEVO"},
 "song-sweet-caroline": {"id": "4F_RCWVoL4s", "title": "Neil Diamond - Sweet Caroline (Audio)", "author_name": "neildiamondVEVO"},
 "song-livin-on-a-prayer": {"id": "lDK9QqIzhwk", "title": "Bon Jovi - Livin' On A Prayer", "author_name": "BonJoviVEVO"},
 "song-i-will-survive": {"id": "6dYWe1c3OyU", "title": "Gloria Gaynor - I Will Survive", "author_name": "GloriaGaynorVEVO"},
 "song-mr-brightside": {"id": "gGdGFtwCNBE", "title": "The Killers - Mr. Brightside (Official Music Video)", "author_name": "TheKillersVEVO"},
 "song-dancing-queen": {"id": "xFrGuyw1V8s", "title": "ABBA - Dancing Queen (Official Music Video)", "author_name": "AbbaVEVO"},
 "song-summer-nights": {"id": "A_J2bcNx3Gw", "title": "Summer Nights (From “Grease”)", "author_name": "John Travolta - Topic"},
 "song-africa": {"id": "FTQbiNvZqaY", "title": "Toto - Africa (Official HD Video)", "author_name": "TotoVEVO"},
 "song-bohemian-rhapsody": {"id": "fJ9rUzIMcZQ", "title": "Queen – Bohemian Rhapsody (Official Video Remastered)", "author_name": "Queen Official"},
 "song-autumn-leaves": {"id": "CpB7-8SGlJ0", "title": "Autumn Leaves", "author_name": "Cannonball Adderley - Topic"},
 "song-all-the-things-you-are": {"id": "ASNSS_G62zw", "title": "All The Things You Are", "author_name": "Ella Fitzgerald - Topic"},
 "song-blue-bossa": {"id": "EUxv3AAaK_Y", "title": "Blue Bossa (Remastered)", "author_name": "Joe Henderson Quintet - Topic"},
 "song-there-will-never-be-another-you": {"id": "rMX1LxBba9g", "title": "There Will Never Be Another You", "author_name": "Chet Baker - Topic"},
 "song-misty": {"id": "UOLEEkYO4MA", "title": "Misty", "author_name": "Erroll Garner - Topic"},
 "song-take-the-a-train": {"id": "r2G1fKYFgVU", "title": "Duke Ellington and His Famous Orchestra - Take the \"A\" Train (Audio)", "author_name": "DukeEllingtonVEVO"},
 "song-so-what": {"id": "zqNTltOGh5c", "title": "Miles Davis - So What (Official Video)", "author_name": "MilesDavisVEVO"},
 "song-stella-by-starlight": {"id": "XGx1HvLV_NQ", "title": "Miles Davis - Stella by Starlight (Official Audio)", "author_name": "MilesDavisVEVO"},
 "song-blue-monk": {"id": "Ww3e1tGvpJ8", "title": "Blue Monk (Album Version)", "author_name": "Thelonious Monk - Topic"},
 "song-almost-blue": {"id": "I5l0jkC71Yk", "title": "Almost Blue", "author_name": "Chet Baker - Topic"},
 "song-amazing-grace": {"id": "LGN64GwVIRM", "title": "Aretha Franklin - Amazing Grace (Official Audio)", "author_name": "Aretha Franklin"},
 "song-when-i-was-your-man": {"id": "ekzHIouo8Q4", "title": "Bruno Mars - When I Was Your Man (Official Music Video)", "author_name": "Bruno Mars"},
 "song-break-my-heart-again": {"id": "HjmBLCbTgDo", "title": "FINNEAS - Break My Heart Again (Official Video)", "author_name": "FINNEAS"},
 "song-can-t-help-falling-in-love": {"id": "vGJTaP6anOU", "title": "Elvis Presley - Can't Help Falling In Love (Official Audio)", "author_name": "ElvisPresleyVEVO"},
 "song-say-you-won-t-let-go": {"id": "KcBhJMc9Ibc", "title": "James Arthur - Say You Won't Let Go (Acoustic Version)", "author_name": "JamesAVEVO"},
 "song-die-for-you": {"id": "uPD0QOGTmMI", "title": "The Weeknd - Die For You", "author_name": "TheWeekndVEVO"},
 "song-all-of-me": {"id": "450p7goxZqg", "title": "John Legend - All of Me (Official Video)", "author_name": "johnlegendVEVO"},
 "song-just-the-way-you-are": {"id": "LjhCEhWiKXk", "title": "Bruno Mars - Just The Way You Are (Official Music Video)", "author_name": "Bruno Mars"},
 "song-november-rain": {"id": "8SbUC-UaAxE", "title": "Guns N' Roses - November Rain", "author_name": "GunsNRosesVEVO"},
 "song-sweet-child-o-mine": {"id": "1w7OgIMMRc4", "title": "Guns N' Roses - Sweet Child O' Mine (Official Music Video)", "author_name": "GunsNRosesVEVO"},
 "song-hotel-california": {"id": "09839DpTctU", "title": "Eagles - Hotel California (Live 1977) (Official Video) [HD]", "author_name": "Eagles"},
 "song-summer-of-69": {"id": "9f06QZCVUHg", "title": "Bryan Adams - Summer Of 69 (Official Music Video)", "author_name": "Bryan Adams"},
 "song-make-you-feel-my-love": {"id": "0put0_a--Ng", "title": "Adele - Make You Feel My Love (Official Video)", "author_name": "XL Recordings"},
 "song-set-fire-to-the-rain": {"id": "a2giXO6eyuI", "title": "Set Fire to the Rain", "author_name": "Adele - Topic"},
 "song-somebody-s-me": {"id": "gv9hrQzU0cA", "title": "Enrique Iglesias - Somebody's Me", "author_name": "EnriqueIglesiasVEVO"},
 "song-still-d-r-e": {"id": "_CL6n0FJZpk", "title": "Dr. Dre - Still D.R.E. ft. Snoop Dogg", "author_name": "DrDreVEVO"},
 "song-25-minutes": {"id": "SIWcOdBtLRw", "title": "Michael Learns To Rock - 25 Minutes [Official Video] (with Lyrics Closed Caption)", "author_name": "Michael Learns To Rock"},
 "song-someday": {"id": "__oCUzwL7i0", "title": "Michael Learns To Rock - Someday [Official Video] (with Lyrics Closed Caption)", "author_name": "Michael Learns To Rock"},
 "song-my-love-mine-all-mine": {"id": "vx4kLgnFexo", "title": "Mitski - My Love Mine All Mine (Official Video)", "author_name": "MitskiVEVO"},
 "song-heart-and-soul": {"id": "JPphPGcjdYM", "title": "Heart and Soul", "author_name": "Larry Clinton & His Orchestra - Topic"},
 "song-hallelujah": {"id": "YrLk4vdY28Q", "title": "Leonard Cohen - Hallelujah (Official Live in London 2008)", "author_name": "LeonardCohenVEVO"},
 "song-imagine": {"id": "YkgkThdzX-8", "title": "IMAGINE. (Ultimate Mix, 2020) - John Lennon & The Plastic Ono Band (with the Flux Fiddlers) HD", "author_name": "johnlennon"},
 "song-happy-birthday-to-you": {"id": "c-v-7JRisLA", "title": "Happy Birthday | Kids Songs | Super Simple Songs", "author_name": "Super Simple Songs - Kids Songs"},
 "song-twinkle-twinkle-little-star": {"id": "yCjJyiqpAuU", "title": "Twinkle Twinkle Little Star | Nursery Rhymes for Kids | Super Simple Songs", "author_name": "Super Simple Songs - Kids Songs"},
 "song-brown-eyed-girl": {"id": "UfmkgQRmmeE", "title": "Van Morrison - Brown Eyed Girl (Official Audio)", "author_name": "VanMorrisonVEVO"},
 "song-three-little-birds": {"id": "HNBCVM4KbUM", "title": "Bob Marley & The Wailers - Three Little Birds (Official Music Video)", "author_name": "BobMarleyVEVO"},
 "song-jingle-bells": {"id": "hLf0-lro8X8", "title": "Frank Sinatra - Jingle Bells (Official Music Video)", "author_name": "FrankSinatraVEVO"},
 "song-hey-jude": {"id": "A_MjCqQoLLA", "title": "The Beatles - The Beatles - Hey Jude (Official Music Video) [Remastered 2015]", "author_name": "TheBeatlesVEVO"},
 "song-autumn-leaves-chet-baker-simplified": {"id": "AFTC1Fg9cXQ", "title": "Autumn Leaves", "author_name": "Chet Baker - Topic"},
 "song-my-funny-valentine-easy-version": {"id": "QuMzUXPEPRM", "title": "My Funny Valentine", "author_name": "Chet Baker - Topic"},
 "song-clocks": {"id": "d020hcWA_Wg", "title": "Coldplay - Clocks (Official Video)", "author_name": "Coldplay"},
 "song-piano-man": {"id": "hRlsu-4BNv8", "title": "Billy Joel - Piano Man (Original Video)", "author_name": "billyjoelVEVO"},
 "song-hello": {"id": "YQHsXMglC9A", "title": "Adele - Hello (Official Music Video)", "author_name": "Adele"},
 "song-counting-stars": {"id": "hT_nvWreIhg", "title": "OneRepublic - Counting Stars", "author_name": "OneRepublicVEVO"},
 "song-comptine-d-un-autre-t": {"id": "znfYwABeSZ0", "title": "Comptine d'un autre été, l'après-midi", "author_name": "Yann Tiersen - Topic"},
 "song-river-flows-in-you": {"id": "7maJOI3QMu0", "title": "Yiruma, (이루마) - River Flows in You", "author_name": "YirumaVEVO"},
 "song-radioactive": {"id": "ktvTqknDobU", "title": "Imagine Dragons - Radioactive", "author_name": "ImagineDragonsVEVO"},
 "song-billie-jean": {"id": "Zi_XLOBDo_Y", "title": "Michael Jackson - Billie Jean (Official Video)", "author_name": "michaeljacksonVEVO"},
 "song-sweet-dreams-are-made-of-this": {"id": "qeMFqkcPYcg", "title": "Eurythmics, Annie Lennox, Dave Stewart - Sweet Dreams (Are Made Of This) (Official Video)", "author_name": "EurythmicsVEVO"},
 "song-fly-me-to-the-moon": {"id": "JYuyWrkwpok", "title": "Frank Sinatra - Fly Me To The Moon (Audio) ft. Count Basie And His Orchestra", "author_name": "FrankSinatraVEVO"},
 "song-take-five": {"id": "-DHuW1h1wHw", "title": "Dave Brubeck, The Dave Brubeck Quartet - Take Five (Audio)", "author_name": "DaveBrubeckVEVO"},
 "song-all-of-me-jazz-standard": {"id": "5J18k5Sx3Dw", "title": "Billie Holiday - All of Me (Official Audio)", "author_name": "BillieHolidayVEVO"},
 "song-summertime": {"id": "2HJCN3upMHE", "title": "Louis Armstrong, Ella Fitzgerald - Summertime (Audio)", "author_name": "EllaFitzgeraldVEVO"},
 "song-satin-doll": {"id": "wQ-n7jhs_K8", "title": "Satin Doll", "author_name": "Duke Ellington - Topic"},
 "song-cantaloupe-island": {"id": "otFVFLtRF_s", "title": "Cantaloupe Island (Remastered 1999/Rudy Van Gelder Edition)", "author_name": "Herbie Hancock - Topic"},
 "song-gymnop-die-no-1": {"id": "EaTjt_iIs2s", "title": "Gymnopédie No. 1", "author_name": "Erik Satie - Topic"},
 "song-prelude-in-c-major-bwv-846": {"id": "gVah1cr3pU0", "title": "Lang Lang – Bach: The Well-Tempered Clavier: Book 1, 1.Prelude C Major, BWV 846", "author_name": "Deutsche Grammophon - DG"},
 "song-the-blue-danube-waltz": {"id": "woWJqKznCSc", "title": "Wiener Philharmoniker, Riccardo Muti - Blue Danube Waltz", "author_name": "WienerPhilVEVO"},
 "song-hungarian-rhapsody-no-2": {"id": "HCRgLae3Ujc", "title": "Liszt: Hungarian Rhapsody No. 2, S. 359/2 (Orch. Doppler/Liszt in D Minor from S. 244/2)", "author_name": "Herbert von Karajan - Topic"},
 "song-while-my-guitar-gently-weeps": {"id": "zOKGcEfSwnY", "title": "The Beatles - While My Guitar Gently Weeps (2018 Mix / Audio)", "author_name": "TheBeatlesVEVO"},
 "song-comfortably-numb": {"id": "7kWl-ZGMwkQ", "title": "Pink Floyd - Comfortably Numb (PULSE Restored & Re-Edited)", "author_name": "Pink Floyd"},
 "song-stairway-to-heaven": {"id": "Ly6ZhQVnVow", "title": "Led Zeppelin - Stairway To Heaven (Live at Earl's Court 1975) [Official Video]", "author_name": "Led Zeppelin"},
 "song-les-champs-elys-es": {"id": "bb-DKKRN4o8", "title": "Joe Dassin - Les Champs-Elysées (Clip officiel)", "author_name": "joedassinVEVO"},
 "song-je-veux": {"id": "0TFNGRYMz1U", "title": "ZAZ - Je veux (Clip officiel)", "author_name": "Zaz Official"},
 "song-papaoutai": {"id": "oiKj0Z_Xnjc", "title": "Stromae - papaoutai (Official Video)", "author_name": "StromaeVEVO"},
 "song-la-vie-en-rose": {"id": "-0KvBnIvTFs", "title": "Edith Piaf - La vie en rose (Audio officiel)", "author_name": "Edith Piaf Officiel"},
 "song-non-je-ne-regrette-rien": {"id": "4r454dad7tc", "title": "Edith Piaf - Non, je ne regrette rien (Audio officiel)", "author_name": "Edith Piaf Officiel"},
 "song-la-bamba": {"id": "0ymdjg9v8zM", "title": "La Bamba", "author_name": "Ritchie Valens - Topic"},
 "song-guantanamera": {"id": "J1VfQVIZKaU", "title": "Guantanamera", "author_name": "Joseito Fernandez - Topic"},
 "song-bailando": {"id": "NUsoVlDFqZg", "title": "Enrique Iglesias - Bailando ft. Descemer Bueno, Gente De Zona", "author_name": "EnriqueIglesiasVEVO"},
 "song-vivir-mi-vida": {"id": "YXnjy5YlDwk", "title": "Marc Anthony - Vivir Mi Vida (Official Video)", "author_name": "marcanthonyVEVO"},
 "song-mas-que-nada": {"id": "hg0XftC43Zo", "title": "Mas, Que Nada!", "author_name": "Jorge Ben Jor - Topic"},
 "song-ai-se-eu-te-pego": {"id": "hcm55lU9knw", "title": "Michel Teló - Ai Se Eu Te Pego -  Video Oficial (Assim você me mata)", "author_name": "Michel Teló"},
 "song-trem-bala": {"id": "sWhy1VcvvgY", "title": "Ana Vilela - Trem-Bala - (Clipe Oficial)", "author_name": "Ana Vilela"},
 "song-tempo-perdido": {"id": "qku-HL1pmYs", "title": "Tempo Perdido", "author_name": "Legiao Urbana - Topic"},
 "song-evid-ncias": {"id": "ePjtnSPFWK8", "title": "Chitãozinho & Xororó - Evidências", "author_name": "CHXVEVO"},
 "song-nel-blu-dipinto-di-blu-volare": {"id": "6jWsIpAbo-8", "title": "Volare (Nel Blu Dipinto Di Blu) (Remastered)", "author_name": "Domenico Modugno - Topic"},
 "song-bella-ciao": {"id": "jEcwLBp2Y80", "title": "Bella ciao (Remastered)", "author_name": "Milva - Topic"},
 "song-l-italiano": {"id": "TYtdYslLY9I", "title": "L'italiano - Toto Cutugno Video Ufficiale", "author_name": "Toto Cutugno"},
 "song-felicit": {"id": "xUj-lfx6vbo", "title": "Al Bano & Romina Power - Felicità (Musikladen 11.03.1982)", "author_name": "AlBanoVEVO"},
 "song-sar-perch-ti-amo": {"id": "IzlY6eehBoE", "title": "Ricchi e Poveri - Sarà perché ti amo (Musicalmente - Ricchi e Poveri, 1981)", "author_name": "RicchiEPoveriVEVO"},
 "song-99-luftballons": {"id": "Fpu5a0Bl8eY", "title": "NENA | 99 Luftballons [1983] [Offizielles HD Musikvideo]", "author_name": "NENA"},
 "song-atemlos-durch-die-nacht": {"id": "haECT-SerHk", "title": "Helene Fischer - Atemlos durch die Nacht", "author_name": "HeleneFischerVEVO"},
 "song-tage-wie-diese": {"id": "j09hpp3AxIE", "title": "Die Toten Hosen // „Tage wie diese\" [Offizielles Musikvideo]", "author_name": "DIE TOTEN HOSEN"},
 "song-auf-uns": {"id": "k9EYjn5f_nE", "title": "Andreas Bourani - Auf uns (Official Video)", "author_name": "Digster Pop Music"},
 "song-stille-nacht-heilige-nacht": {"id": "vKvKMgR8H7k", "title": "Vienna Boys Choir - Stille Nacht (Silent Night)", "author_name": "Wiener Sängerknaben / Vienna Boys Choir (official)"},
 "song-tum-hi-ho": {"id": "WWZxDA81JFk", "title": "Tum Hi Ho Aashiqui 2 Full Video Song | Aditya Roy Kapur, Shraddha Kapoor", "author_name": "T-Series"},
 "song-channa-mereya": {"id": "284Ov7ysmfA", "title": "Channa Mereya Full Video - ADHM | Ranbir Kapoor, Anushka | Arijit Singh | Pritam | Karan Johar", "author_name": "Sony Music India"},
 "song-kesariya": {"id": "BddP6PYo2gs", "title": "Kesariya - Brahmāstra | Ranbir Kapoor, Alia Bhatt | Pritam | Arijit Singh | Amitabh Bhattacharya| 4K", "author_name": "Sony Music India"},
 "song-agar-tum-saath-ho": {"id": "xRb8hxwN5zc", "title": "'AGAR TUM SAATH HO' Full VIDEO song | Tamasha | Ranbir Kapoor, Deepika Padukone | T-Series", "author_name": "T-Series"},
 "song-pal-pal-dil-ke-paas": {"id": "AMuRRXCuy-4", "title": "Blackmail - Pal Pal Dil Ke Paas Tum Rehti Ho - Kishore Kumar", "author_name": "Shemaroo"},
 "song-ue-o-muite-aruk-sukiyaki": {"id": "F284iB65-QU", "title": "Sukiyaki", "author_name": "Kyu Sakamoto - Topic"},
 "song-lemon": {"id": "SX_ViT4Ra7k", "title": "米津玄師  Kenshi Yonezu  - Lemon", "author_name": "Kenshi Yonezu  米津玄師"},
 "song-marigold": {"id": "0xSiBpUdW4E", "title": "あいみょん - マリーゴールド【OFFICIAL MUSIC VIDEO】", "author_name": "あいみょん"},
 "song-plastic-love": {"id": "T_lC2O1oIew", "title": "竹内まりや -  Plastic Love (Official Music Video)", "author_name": "竹内まりや - Mariya Takeuchi Official YouTube Channel"},
 "song-spring-day": {"id": "xEeFrLSkMm8", "title": "BTS (방탄소년단) '봄날 (Spring Day)' Official MV", "author_name": "HYBE LABELS"},
 "song-love-scenario": {"id": "vecSVX1QYbQ", "title": "iKON - ‘사랑을 했다(LOVE SCENARIO)’ M/V", "author_name": "iKON"},
 "song-through-the-night": {"id": "B-4Y_OVBpto", "title": "IU(아이유) - Through the Night(밤편지) (Sketchbook) | KBS WORLD TV 200918", "author_name": "KBS WORLD TV"},
 "song-stay-with-me": {"id": "pcKR0LPwoYs", "title": "[도깨비 OST Part 1] 찬열, 펀치 (CHANYEOL, PUNCH) - Stay With Me MV", "author_name": "STONE MUSIC"},
 "song-eight": {"id": "tJM0yIbg8iQ", "title": "[IU] 'eight' Acoustic Ver. Live Clip", "author_name": "이지금 [IU Official]"},
 "song-the-moon-represents-my-heart-yu-li-ng-d-ibi-o-w-de-x-n": {"id": "IgvDMB5fR-8", "title": "月亮代表我的心", "author_name": "Teresa Teng - Topic"},
 "song-ti-n-m-m": {"id": "5eF8oOWtsk4", "title": "鄧麗君 Teresa Teng テレサ・テン - 甜蜜蜜 (Official Music Video)", "author_name": "TeresaTengVEVO"},
 "song-sunny-day-q-ng-ti-n": {"id": "DYptgVvkVLQ", "title": "周杰倫 Jay Chou【晴天 Sunny Day】-Official Music Video", "author_name": "周杰倫 Jay Chou"},
 "song-fairy-tale-t-ng-hu": {"id": "bBcp_ljCBGU", "title": "光良 Michael Wong【童話】Official Music Video", "author_name": "滾石唱片 ROCK RECORDS"},
 "song-mouse-loves-rice-l-osh-i-d-m": {"id": "zwT8iOwj9Ms", "title": "2011年网络春晚 歌曲《老鼠爱大米》 杨臣刚| CCTV春晚", "author_name": "CCTV春晚"},
 "song-tamally-maak": {"id": "EgmXTmj62ic", "title": "@AmrDiab - Tamally Maak | Official Music Video - HD Version | عمرو دياب - تملي معاك", "author_name": "Mazzika - مزيكا"},
 "song-habibi-ya-nour-el-ein": {"id": "KLJA-srM_yM", "title": "Amr Diab - Nour El Ein | Official Music Video - HD Version | عمرو دياب - نور العين", "author_name": "Mazzika - مزيكا"},
 "song-ya-rayah": {"id": "vBu2OXGWBFI", "title": "Rachid Taha - Ya Rayah", "author_name": "RachidTahaVEVO"},
 "song-lamma-bada-yatathanna": {"id": "AhBeeVYkDe8", "title": "Lamma Bada Yatathanna - Fairuz | لما بدا يتثنى - فيروز", "author_name": "Fairuz"},
 "song-blank-space": {"id": "e-ORhEE9VVg", "title": "Taylor Swift - Blank Space", "author_name": "Taylor Swift"},
 "song-bad-romance": {"id": "qrO4YZeyl0I", "title": "Lady Gaga - Bad Romance (Official Music Video)", "author_name": "LadyGagaVEVO"},
 "song-what-was-i-made-for": {"id": "cW8VLC9nnTo", "title": "Billie Eilish - What Was I Made For? (Official Music Video)", "author_name": "BillieEilishVEVO"},
 "song-ocean-eyes": {"id": "viimfQi_pUw", "title": "Billie Eilish - ocean eyes (Official Music Video)", "author_name": "Billie Eilish"},
 "song-when-the-party-s-over": {"id": "pbMwTqkKSps", "title": "Billie Eilish - when the party's over", "author_name": "BillieEilishVEVO"},
 "song-karma-police": {"id": "1uYWYWPc9HU", "title": "Radiohead - Karma Police", "author_name": "Radiohead"},
 "song-no-surprises": {"id": "u5CVsCnxyXg", "title": "Radiohead - No Surprises", "author_name": "Radiohead"},
 "song-everything-in-its-right-place": {"id": "NUnXxh5U25Y", "title": "Everything In Its Right Place", "author_name": "Radiohead - Topic"},
 "song-pyramid-song": {"id": "3M_Gg1xAHE4", "title": "Radiohead - Pyramid Song", "author_name": "Radiohead"},
 "song-i-want-it-that-way": {"id": "4fndeDfaWCg", "title": "Backstreet Boys - I Want It That Way (Official HD Video)", "author_name": "BackstreetBoysVEVO"},
 "song-man-i-feel-like-a-woman": {"id": "ZJL4UGSbeFg", "title": "Shania Twain - Man! I Feel Like A Woman! (Official Music Video)", "author_name": "ShaniaTwainVEVO"},
 "song-total-eclipse-of-the-heart": {"id": "lcOxhH8N3Bo", "title": "Bonnie Tyler - Total Eclipse of the Heart (Turn Around) (Official Video)", "author_name": "bonnietylerVEVO"},
 "song-take-on-me": {"id": "djV11Xbc914", "title": "a-ha - Take On Me (Official Video) [4K]", "author_name": "a-ha"},
 "song-like-a-prayer": {"id": "79fzeNUqQbQ", "title": "Madonna - Like A Prayer (Official Video)", "author_name": "Madonna"},
 "song-valerie": {"id": "bixuI_GV5I0", "title": "Mark Ronson ft. Amy Winehouse - Valerie (Official Video)", "author_name": "MarkRonsonVEVO"},
 "song-before-he-cheats": {"id": "WaSy8yy-mr8", "title": "Carrie Underwood - Before He Cheats (Official Video)", "author_name": "carrieunderwoodVEVO"},
 "song-pata-pata": {"id": "SBH_u-vEK30", "title": "Pata Pata (Stereo Version)", "author_name": "Miriam Makeba - Topic"},
 "song-hava-nagila": {"id": "620GF7XSPBM", "title": "Hava Nagila", "author_name": "Harry Belafonte - Topic"},
 "song-hopp-polla": {"id": "JAYb8ZyjzD0", "title": "Sigur Rós - Hoppípolla  [Official Music Video - 4K]", "author_name": "Sigur Rós"},
 "song-dilemma": {"id": "8WYHDfJDPDc", "title": "Nelly - Dilemma (Official Music Video) ft. Kelly Rowland", "author_name": "NellyVEVO"},
 "song-hot-in-herre": {"id": "GeZZr_p6vB8", "title": "Nelly - Hot In Herre (Official Music Video)", "author_name": "NellyVEVO"},
 "song-i-m-like-a-bird": {"id": "roPQ_M3yJTA", "title": "Nelly Furtado - I'm Like A Bird (Official Music Video)", "author_name": "NellyFurtadoVEVO"},
 "song-bubbly": {"id": "AWGqoCNbsvM", "title": "Colbie Caillat - Bubbly (Official Music Video)", "author_name": "ColbieCaillatVEVO"},
 "song-like-a-star": {"id": "htmE_cSDtwM", "title": "Corinne Bailey Rae - Like A Star", "author_name": "CorinneBaileyRaeVEVO"},
 "song-anak": {"id": "ibmh64itn1M", "title": "Freddie Aguilar — Anak [Official Lyric Video with Chords]", "author_name": "Viva Records"},
 "song-tadhana": {"id": "TjEbuWP3hjg", "title": "Tadhana - Up Dharma Down (Official Lyric Video)", "author_name": "Viva Records"},
 "song-sukiyaki": {"id": "F284iB65-QU", "title": "Sukiyaki", "author_name": "Kyu Sakamoto - Topic"},
 "song-kal-ho-naa-ho": {"id": "g0eO74UmRBs", "title": "Kal Ho Naa Ho (Title Track) - Full Video | Shah Rukh Khan, Saif Ali Khan, Preity Zinta | Sonu Nigam", "author_name": "Sony Music India"},
 "song-volare-nel-blu-dipinto-di-blu": {"id": "6jWsIpAbo-8", "title": "Volare (Nel Blu Dipinto Di Blu) (Remastered)", "author_name": "Domenico Modugno - Topic"},
 "song-dragostea-din-tei": {"id": "YnopHCL1Jk8", "title": "O-Zone - Dragostea Din Tei [Official Video]", "author_name": "Time Records"},
 "song-jerusalema": {"id": "fCZVL_8D048", "title": "Master KG - Jerusalema  [Feat. Nomcebo] (Official Music Video)", "author_name": "Openmic Productions"},
 "song-vintersaga": {"id": "i7OeYc4B-eQ", "title": "Vintersaga", "author_name": "Monica Törnell - Topic"},
 "song-ode-to-joy": {"id": "9J0bjyJ13tQ", "title": "Beethoven - Symphony No. 9: Freude Schöner Götterfunken, Ode to Joy | National Anthem of Europe", "author_name": "EuroArtsChannel"},
 "song-minuet-in-g-major": {"id": "LPpfXF4RYXA", "title": "Petzold: Minuet in G Major (Prev. Attrib. J.S. Bach as BWV Anh. 114)", "author_name": "Lang Lang - Topic"},
 "song-f-r-elise": {"id": "s71I_EWJk7I", "title": "\"Für Elise\" Performed by Lang Lang", "author_name": "Steinway & Sons"},
 "song-canon-in-d": {"id": "JvNQLJ1_HQ0", "title": "Pachelbel Canon in D Major - the original and best version.", "author_name": "Voices of Music"},
 "song-symphony-no-5-theme": {"id": "H1rTXpnmzrs", "title": "Symphony No. 5 (1st movement) / Ludwig van Beethoven / Herbert Blomstedt / Oslo Philharmonic", "author_name": "Oslo Philharmonic"},
 "song-morning-mood": {"id": "J-1Bob1dU18", "title": "Grieg: Peer Gynt Suite No. 1, Op. 46: I. Morning Mood", "author_name": "Berliner Philharmoniker - Topic"},
 "song-moonlight-sonata-3rd-movement": {"id": "zucBfXpCA6s", "title": "Beethoven \"Moonlight\" Sonata,  III \"Presto Agitato\" Valentina Lisitsa", "author_name": "Valentina Lisitsa QOR Records Official channel"},
 "song-la-campanella": {"id": "NGGVJcsLi98", "title": "Liszt: Grandes Études de Paganini, S. 141: No. 3 in G-Sharp Minor \"La Campanella\"", "author_name": "Daniil Trifonov - Topic"},
 "song-fantaisie-impromptu": {"id": "Gy5UHK4EeM8", "title": "Daniil Trifonov – Chopin: Fantaisie-Impromptu In C-Sharp Minor, Op. 66", "author_name": "Deutsche Grammophon - DG"},
 "song-piano-concerto-no-2": {"id": "caR7C2SHdFI", "title": "Rachmaninoff: Piano Concerto No. 2 in C Minor, Op. 18: I. Moderato", "author_name": "Krystian Zimerman - Topic"},
 "song-chasse-neige": {"id": "ANCV3uG1GBg", "title": "Yunchan Lim 임윤찬 – LISZT – 12 Transcendental Etudes No. 12 (Chasse-neige)", "author_name": "The Cliburn"},
 "song-clair-de-lune": {"id": "U3u4pQ4WKOk", "title": "Seong-Jin Cho – Debussy: Suite bergamasque, L.75: III. Clair de lune", "author_name": "Deutsche Grammophon - DG"},
 "song-nocturne-in-e-flat-major-op-9-no-2": {"id": "QR10Od1cLaM", "title": "Seong-Jin Cho – Chopin: Nocturnes, Op. 9: No. 2 in E Flat Major. Andante", "author_name": "Deutsche Grammophon - DG"},
 "song-rondo-alla-turca": {"id": "n2Tru4Qa3pc", "title": "YUNDI plays Mozart: Piano Sonata No. 11 in A Major, K. 331 \"Alla Turca\": III. Rondo alla Turca", "author_name": "Warner Classics"},
 "song-revolutionary-tude": {"id": "TgBz7LnvUaQ", "title": "Seong-Jin Cho – Chopin: Etude in C Minor, Op. 10 No. 12 \"Revolutionary\"", "author_name": "Deutsche Grammophon - DG"},
 "song-tennessee-whiskey": {"id": "l6_w3887Rwo", "title": "Tennessee Whiskey", "author_name": "Chris Stapleton - Topic"},
 "song-angels": {"id": "luwAMFcc2f8", "title": "Robbie Williams - Angels", "author_name": "robbiewilliamsvevo"},
 "song-my-way": {"id": "qQzdAsjWGPg", "title": "My Way (2008 Remastered)", "author_name": "Frank Sinatra - Topic"},
 "song-lose-control": {"id": "LweyzRnEzOE", "title": "Lose Control", "author_name": "Teddy Swims - Topic"},
 "song-a-cha": {"id": "gzlHucbD76U", "title": "Khaled - Aicha", "author_name": "KhaledMusicVEVO"},
 "song-shchedryk": {"id": "ReSHW69mU4w", "title": "AUSTRALIAN CHAMBER CHOIR Ukrainian Bell Carol (Shchedryk), by Mykola Leontovych", "author_name": "AUSTRALIAN CHAMBER CHOIR"},
 "song-zorba-s-dance": {"id": "Xsen9Jh-TPo", "title": "Zorba's Dance - Mikis Theodorakis [Original Score]", "author_name": "FM Records"},
 "song-mar-k": {"id": "cpp69ghR1IM", "title": "TARKAN - Şımarık (Official Music Video)", "author_name": "Tarkan"},
 "song-enter-sandman": {"id": "CD-E-LDc384", "title": "Metallica: Enter Sandman (Official Music Video)", "author_name": "Metallica"},
 "song-nothing-else-matters": {"id": "tAGnKpE4NCI", "title": "Metallica: Nothing Else Matters (Official Music Video)", "author_name": "Metallica"},
 "song-master-of-puppets": {"id": "E0ozmU9cJDg", "title": "Master of Puppets (Remastered)", "author_name": "Metallica - Topic"},
 "song-one": {"id": "WM8bTdBs-cw", "title": "Metallica: One (Official Music Video)", "author_name": "Metallica"},
 "song-for-whom-the-bell-tolls": {"id": "B_HSa1dEL9s", "title": "For Whom The Bell Tolls (Remastered)", "author_name": "Metallica - Topic"},
 "song-the-unforgiven": {"id": "DDGhKS6bSAE", "title": "Metallica: The Unforgiven (Official Music Video)", "author_name": "Metallica"},
 "song-whiskey-in-the-jar": {"id": "wsrvmNtWU4E", "title": "Metallica - Whiskey In The Jar (Official Music Video)", "author_name": "Warner Records Vault"},
 "song-sad-but-true": {"id": "A8MO7fkZc5o", "title": "Metallica: Sad But True (Official Music Video)", "author_name": "Metallica"},
 "song-fade-to-black": {"id": "9HZ_tx8aWuA", "title": "Fade To Black (Remastered)", "author_name": "Metallica - Topic"},
 "song-fuel": {"id": "G1cjHbXdU0s", "title": "Metallica: Fuel (Official Music Video)", "author_name": "Metallica"},
 "song-seek-destroy": {"id": "FLTchCiC0T0", "title": "Seek & Destroy (Remastered)", "author_name": "Metallica - Topic"},
 "song-wherever-i-may-roam": {"id": "dHUHxTiPFUU", "title": "Metallica: Wherever I May Roam (Official Music Video)", "author_name": "Metallica"},
 "song-paranoid": {"id": "0qanF-91aJo", "title": "BLACK SABBATH - \"Paranoid\" (Official Video)", "author_name": "Black Sabbath"},
 "song-iron-man": {"id": "b3-QqGVt-tM", "title": "Iron Man (2012 Remaster)", "author_name": "Black Sabbath - Topic"},
 "song-crazy-train": {"id": "FVovq9TGBw0", "title": "OZZY OSBOURNE - \"Crazy Train\" (Official Video)", "author_name": "Ozzy Osbourne"},
 "song-breaking-the-law": {"id": "L397TWLwrUU", "title": "Judas Priest - Breaking The Law (Official Music Video)", "author_name": "JudasPriestVEVO"},
 "song-run-to-the-hills": {"id": "86URGgqONvA", "title": "Iron Maiden - Run To The Hills (Official Video)", "author_name": "Iron Maiden"},
 "song-the-trooper": {"id": "X4bgXH3sJ2Q", "title": "Iron Maiden - The Trooper (Official Video)", "author_name": "Iron Maiden"},
 "song-fear-of-the-dark": {"id": "bePCRKGUwAY", "title": "Fear of the Dark (2015 Remaster)", "author_name": "Iron Maiden - Topic"},
 "song-in-the-end": {"id": "eVTXPUF4Oz4", "title": "In The End [Official HD Music Video] - Linkin Park", "author_name": "Linkin Park"},
 "song-numb": {"id": "kXYiU_JCYtU", "title": "Numb (Official Music Video) [4K UPGRADE] – Linkin Park", "author_name": "Linkin Park"},
 "song-what-i-ve-done": {"id": "8sgycukafqQ", "title": "What I've Done (Official Music Video) [4K Upgrade] - Linkin Park", "author_name": "Linkin Park"},
 "song-bring-me-to-life": {"id": "3YxaaGgTQYM", "title": "Evanescence - Bring Me To Life (Official HD Music Video) ft. Paul McCoy", "author_name": "EvanescenceVEVO"},
 "song-snuff": {"id": "LXEKuttVRIo", "title": "Slipknot - Snuff [OFFICIAL VIDEO] [HD]", "author_name": "Slipknot"},
 "song-the-sound-of-silence": {"id": "u9Dg-g7t2l4", "title": "Disturbed  - The Sound Of Silence (Official Music Video) [4K UPGRADE]", "author_name": "Disturbed"},
 "song-drown": {"id": "TkV5709EG5M", "title": "Bring Me The Horizon - Drown", "author_name": "BMTHOfficialVEVO"},
 "song-sekai-ni-hitotsu-dake-no-hana-v": {"id": "b7ruJQM0A0I", "title": "Sekai Ni Hitotsu Dake No Hana (Live At Nippon Budokan / 2005)", "author_name": "Noriyuki Makihara - Topic"},
 "song-ya-lili-v": {"id": "IJHPpTYtIqk", "title": "Balti feat. Hamouda - Ya Lili (Official Music Video)", "author_name": "Thisiz Balti", "noEmbed": true}
};
const SONG_VIDEOS = {
 "Bamboléo": "bambol-o-live-v2",
 "Creep": "creep",
 "The A Team": "the-a-team",
 "Perfect": "perfect-acoustic-v2",
 "Viva La Vida": "viva-la-vida",
 "Take Me Home, Country Roads": "country-roads",
 "Linger": "linger",
 "Love Story": "love-story-acoustic-v2",
 "Let It Be": "let-it-be",
 "Stand By Me": "stand-by-me-live-v2",
 "Someone Like You": "someone-like-you",
 "No Woman No Cry": "no-woman-no-cry",
 "Don't Stop Believin'": "dont-stop-believin",
 "My Funny Valentine": "my-funny-valentine",
 "Bad Guy": "song-bad-guy",
 "Last Christmas": "song-last-christmas",
 "All I Want for Christmas Is You": "song-all-i-want-for-christmas-is-you",
 "Die With a Smile": "die-with-a-smile-live-v2",
 "Blinding Lights": "song-blinding-lights",
 "Shape of You": "shape-of-you-live-v2",
 "Sweater Weather": "sweater-weather-acoustic-v2",
 "Starboy": "song-starboy",
 "As It Was": "as-it-was-acoustic-v2",
 "Someone You Loved": "someone-you-loved-acoustic-v2",
 "Sunflower": "song-sunflower",
 "One Dance": "one-dance-live-v2",
 "Stay": "song-stay",
 "Believer": "believer-acoustic-v2",
 "I Wanna Be Yours": "i-wanna-be-yours-acoustic-v2",
 "Heat Waves": "heat-waves-acoustic-v2",
 "Yellow": "yellow-acoustic-v2",
 "The Night We Met": "the-night-we-met-live-v2",
 "Closer": "song-closer",
 "Something Just Like This": "something-just-like-this-live-v2",
 "Riptide": "riptide-acoustic-v2",
 "Levitating": "song-levitating",
 "Lucid Dreams": "song-lucid-dreams",
 "Photograph": "photograph-acoustic-v2",
 "You Belong With Me": "song-you-belong-with-me",
 "Lover": "lover-acoustic-v2",
 "Shake It Off": "shake-it-off-acoustic-v2",
 "Wildest Dreams": "wildest-dreams-acoustic-v2",
 "Shallow": "shallow-live-v2",
 "Million Reasons": "song-million-reasons",
 "Always Remember Us This Way": "song-always-remember-us-this-way",
 "Have Yourself a Merry Little Christmas": "song-have-yourself-a-merry-little-christmas",
 "Thinking Out Loud": "thinking-out-loud-acoustic-v2",
 "Galway Girl": "galway-girl-acoustic-v2",
 "Drop It Like It's Hot": "song-drop-it-like-it-s-hot",
 "Gin and Juice": "song-gin-and-juice",
 "Young, Wild & Free": "song-young-wild-free",
 "With or Without You": "with-or-without-you-live-v2",
 "I'm Yours": "i-m-yours-live-v2",
 "Despacito": "song-despacito",
 "Let Her Go": "let-her-go-acoustic-v2",
 "A Horse With No Name": "a-horse-with-no-name-live-v2",
 "Knockin' on Heaven's Door": "knockin-on-heaven-s-door-acoustic-v2",
 "Wonderwall": "wonderwall-acoustic-v2",
 "Love Yourself": "love-yourself-live-v2",
 "Count on Me": "song-count-on-me",
 "Zombie": "zombie-live-v2",
 "Hey Soul Sister": "hey-soul-sister-acoustic-v2",
 "Let It Go": "song-let-it-go",
 "Budapest": "song-budapest",
 "Sweet Home Alabama": "sweet-home-alabama-live-v2",
 "Wonderful Tonight": "song-wonderful-tonight",
 "Over the Rainbow": "song-over-the-rainbow",
 "Chasing Cars": "chasing-cars-live-v2",
 "Happy": "song-happy",
 "Banana Pancakes": "banana-pancakes-acoustic-v2",
 "Can You Feel the Love Tonight": "song-can-you-feel-the-love-tonight",
 "Sweet Caroline": "sweet-caroline-live-v2",
 "Livin' on a Prayer": "livin-on-a-prayer-live-v2",
 "I Will Survive": "song-i-will-survive",
 "Mr. Brightside": "mr-brightside-live-v2",
 "Dancing Queen": "dancing-queen-live-v2",
 "Summer Nights": "song-summer-nights",
 "Africa": "song-africa",
 "Bohemian Rhapsody": "song-bohemian-rhapsody",
 "Autumn Leaves": "song-autumn-leaves",
 "All the Things You Are": "song-all-the-things-you-are",
 "Blue Bossa": "song-blue-bossa",
 "There Will Never Be Another You": "song-there-will-never-be-another-you",
 "Misty": "song-misty",
 "Take the A Train": "song-take-the-a-train",
 "So What": "song-so-what",
 "Stella by Starlight": "song-stella-by-starlight",
 "Blue Monk": "song-blue-monk",
 "Almost Blue": "song-almost-blue",
 "Amazing Grace": "song-amazing-grace",
 "When I Was Your Man": "song-when-i-was-your-man",
 "Break My Heart Again": "song-break-my-heart-again",
 "Can't Help Falling in Love": "can-t-help-falling-in-love-live-v2",
 "Say You Won't Let Go": "song-say-you-won-t-let-go",
 "Die for You": "song-die-for-you",
 "All of Me": "song-all-of-me",
 "Just the Way You Are": "song-just-the-way-you-are",
 "November Rain": "song-november-rain",
 "Sweet Child O' Mine": "sweet-child-o-mine-live-v2",
 "Hotel California": "song-hotel-california",
 "Summer of '69": "summer-of-69-live-v2",
 "Make You Feel My Love": "song-make-you-feel-my-love",
 "Set Fire to the Rain": "song-set-fire-to-the-rain",
 "Somebody's Me": "somebody-s-me-live-v2",
 "Still D.R.E.": "song-still-d-r-e",
 "25 Minutes": "song-25-minutes",
 "Someday": "song-someday",
 "My Love Mine All Mine": "my-love-mine-all-mine-live-v2",
 "Heart and Soul": "song-heart-and-soul",
 "Hallelujah": "song-hallelujah",
 "Imagine": "song-imagine",
 "Happy Birthday to You": "song-happy-birthday-to-you",
 "Twinkle Twinkle Little Star": "song-twinkle-twinkle-little-star",
 "Brown Eyed Girl": "brown-eyed-girl-live-v2",
 "Three Little Birds": "song-three-little-birds",
 "Jingle Bells": "song-jingle-bells",
 "Hey Jude": "song-hey-jude",
 "Autumn Leaves (Chet Baker, simplified)": "song-autumn-leaves-chet-baker-simplified",
 "My Funny Valentine (easy version)": "song-my-funny-valentine-easy-version",
 "Clocks": "clocks-live-v2",
 "Piano Man": "song-piano-man",
 "Hello": "song-hello",
 "Counting Stars": "counting-stars-live-v2",
 "Comptine d'un autre été": "song-comptine-d-un-autre-t",
 "River Flows in You": "song-river-flows-in-you",
 "Radioactive": "radioactive-live-v2",
 "Billie Jean": "song-billie-jean",
 "Sweet Dreams (Are Made of This)": "sweet-dreams-are-made-of-this-live-v2",
 "Fly Me to the Moon": "song-fly-me-to-the-moon",
 "Take Five": "song-take-five",
 "All of Me (jazz standard)": "song-all-of-me-jazz-standard",
 "Summertime": "song-summertime",
 "Satin Doll": "song-satin-doll",
 "Cantaloupe Island": "song-cantaloupe-island",
 "Gymnopédie No. 1": "song-gymnop-die-no-1",
 "Prelude in C major, BWV 846": "song-prelude-in-c-major-bwv-846",
 "The Blue Danube (waltz)": "song-the-blue-danube-waltz",
 "Hungarian Rhapsody No. 2": "song-hungarian-rhapsody-no-2",
 "While My Guitar Gently Weeps": "while-my-guitar-gently-weeps-official-v2",
 "Comfortably Numb": "song-comfortably-numb",
 "Stairway to Heaven": "song-stairway-to-heaven",
 "Les Champs-Elysées": "song-les-champs-elys-es",
 "Je veux": "je-veux-live-v2",
 "Papaoutai": "papaoutai-live-v2",
 "La Vie en rose": "song-la-vie-en-rose",
 "Non, je ne regrette rien": "song-non-je-ne-regrette-rien",
 "La Bamba": "song-la-bamba",
 "Guantanamera": "song-guantanamera",
 "Bailando": "song-bailando",
 "Vivir Mi Vida": "song-vivir-mi-vida",
 "Mas Que Nada": "song-mas-que-nada",
 "Ai Se Eu Te Pego": "song-ai-se-eu-te-pego",
 "Trem-Bala": "song-trem-bala",
 "Tempo Perdido": "song-tempo-perdido",
 "Evidências": "evid-ncias-live-v2",
 "Nel blu, dipinto di blu (Volare)": "nel-blu-dipinto-di-blu-volare-live-v2",
 "Bella Ciao": "song-bella-ciao",
 "L'Italiano": "song-l-italiano",
 "Felicità": "song-felicit",
 "Sarà perché ti amo": "song-sar-perch-ti-amo",
 "99 Luftballons": "song-99-luftballons",
 "Atemlos durch die Nacht": "song-atemlos-durch-die-nacht",
 "Tage wie diese": "song-tage-wie-diese",
 "Auf uns": "song-auf-uns",
 "Stille Nacht, heilige Nacht": "song-stille-nacht-heilige-nacht",
 "Tum Hi Ho": "song-tum-hi-ho",
 "Channa Mereya": "song-channa-mereya",
 "Kesariya": "song-kesariya",
 "Agar Tum Saath Ho": "song-agar-tum-saath-ho",
 "Pal Pal Dil Ke Paas": "song-pal-pal-dil-ke-paas",
 "Ue o Muite Arukō (Sukiyaki)": "song-ue-o-muite-aruk-sukiyaki",
 "Lemon": "lemon-live-v2",
 "Marigold": "marigold-live-v2",
 "Plastic Love": "plastic-love-live-v2",
 "Spring Day": "spring-day-live-v2",
 "Love Scenario": "love-scenario-live-v2",
 "Through the Night": "song-through-the-night",
 "Stay With Me": "stay-with-me-live-v2",
 "Eight": "song-eight",
 "The Moon Represents My Heart (Yuèliàng Dàibiǎo Wǒ de Xīn)": "song-the-moon-represents-my-heart-yu-li-ng-d-ibi-o-w-de-x-n",
 "Tián Mì Mì": "song-ti-n-m-m",
 "Sunny Day (Qíng Tiān)": "sunny-day-q-ng-ti-n-live-v2",
 "Fairy Tale (Tóng Huà)": "fairy-tale-t-ng-hu-live-v2",
 "Mouse Loves Rice (Lǎoshǔ Ài Dàmǐ)": "song-mouse-loves-rice-l-osh-i-d-m",
 "Tamally Maak": "song-tamally-maak",
 "Habibi Ya Nour El Ein": "song-habibi-ya-nour-el-ein",
 "Ya Rayah": "song-ya-rayah",
 "Lamma Bada Yatathanna": "song-lamma-bada-yatathanna",
 "Blank Space": "blank-space-acoustic-v2",
 "Bad Romance": "song-bad-romance",
 "What Was I Made For?": "song-what-was-i-made-for",
 "Ocean Eyes": "song-ocean-eyes",
 "When the Party's Over": "song-when-the-party-s-over",
 "Karma Police": "karma-police-live-v2",
 "No Surprises": "no-surprises-live-v2",
 "Everything In Its Right Place": "song-everything-in-its-right-place",
 "Pyramid Song": "song-pyramid-song",
 "I Want It That Way": "song-i-want-it-that-way",
 "Man! I Feel Like a Woman!": "song-man-i-feel-like-a-woman",
 "Total Eclipse of the Heart": "song-total-eclipse-of-the-heart",
 "Take On Me": "take-on-me-live-v2",
 "Like a Prayer": "song-like-a-prayer",
 "Valerie": "song-valerie",
 "Before He Cheats": "before-he-cheats-acoustic-v2",
 "Pata Pata": "pata-pata-live-v2",
 "Hava Nagila": "song-hava-nagila",
 "Hoppípolla": "song-hopp-polla",
 "Dilemma": "song-dilemma",
 "Hot in Herre": "song-hot-in-herre",
 "I'm Like a Bird": "i-m-like-a-bird-acoustic-v2",
 "Bubbly": "bubbly-acoustic-v2",
 "Like a Star": "like-a-star-acoustic-v2",
 "Anak": "anak-live-v2",
 "Tadhana": "tadhana-live-v2",
 "Sukiyaki": "song-sukiyaki",
 "Kal Ho Naa Ho": "song-kal-ho-naa-ho",
 "Volare (Nel blu, dipinto di blu)": "volare-nel-blu-dipinto-di-blu-live-v2",
 "Dragostea Din Tei": "song-dragostea-din-tei",
 "Jerusalema": "song-jerusalema",
 "Vintersaga": "song-vintersaga",
 "Ode to Joy": "song-ode-to-joy",
 "Minuet in G Major": "song-minuet-in-g-major",
 "Für Elise": "song-f-r-elise",
 "Canon in D": "song-canon-in-d",
 "Symphony No. 5 (Theme)": "song-symphony-no-5-theme",
 "Morning Mood": "song-morning-mood",
 "Moonlight Sonata (3rd Movement)": "song-moonlight-sonata-3rd-movement",
 "La Campanella": "song-la-campanella",
 "Fantaisie-Impromptu": "song-fantaisie-impromptu",
 "Piano Concerto No. 2": "song-piano-concerto-no-2",
 "Chasse-Neige": "song-chasse-neige",
 "Clair de Lune": "song-clair-de-lune",
 "Nocturne in E-flat Major, Op. 9 No. 2": "song-nocturne-in-e-flat-major-op-9-no-2",
 "Rondo alla Turca": "song-rondo-alla-turca",
 "Revolutionary Étude": "song-revolutionary-tude",
 "Tennessee Whiskey": "tennessee-whiskey-live-v2",
 "Angels": "song-angels",
 "My Way": "song-my-way",
 "Lose Control": "lose-control-acoustic-v2",
 "Aïcha": "a-cha-acoustic-v2",
 "Shchedryk": "song-shchedryk",
 "Zorba's Dance": "song-zorba-s-dance",
 "Şımarık": "song-mar-k",
 "Enter Sandman": "enter-sandman-acoustic-v2",
 "Nothing Else Matters": "nothing-else-matters-live-v2",
 "Master of Puppets": "master-of-puppets-live-v2",
 "One": "one-live-v2",
 "For Whom the Bell Tolls": "for-whom-the-bell-tolls-live-v2",
 "The Unforgiven": "the-unforgiven-acoustic-v2",
 "Whiskey in the Jar": "whiskey-in-the-jar-live-v2",
 "Sad but True": "sad-but-true-live-v2",
 "Fade to Black": "fade-to-black-live-v2",
 "Fuel": "fuel-live-v2",
 "Seek & Destroy": "seek-destroy-live-v2",
 "Wherever I May Roam": "wherever-i-may-roam-live-v2",
 "Paranoid": "paranoid-live-v2",
 "Iron Man": "iron-man-live-v2",
 "Crazy Train": "crazy-train-live-v2",
 "Breaking the Law": "breaking-the-law-live-v2",
 "Run to the Hills": "run-to-the-hills-live-v2",
 "The Trooper": "the-trooper-live-v2",
 "Fear of the Dark": "fear-of-the-dark-live-v2",
 "In the End": "in-the-end-live-v2",
 "Numb": "numb-live-v2",
 "What I've Done": "what-i-ve-done-live-v2",
 "Bring Me to Life": "song-bring-me-to-life",
 "Snuff": "snuff-acoustic-v2",
 "The Sound of Silence": "the-sound-of-silence-live-v2",
 "Drown": "drown-live-v2",
 "Sekai ni Hitotsu Dake no Hana": "song-sekai-ni-hitotsu-dake-no-hana-v",
 "Ya Lili": "song-ya-lili-v"
};
export { PEOPLE, VIDEOS, SONG_VIDEOS };
